// Code generated by ent, DO NOT EDIT.

package list

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the list type in the database.
	Label = "list"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSynchronizedAt holds the string denoting the synchronized_at field in the database.
	FieldSynchronizedAt = "synchronized_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStackSize holds the string denoting the stack_size field in the database.
	FieldStackSize = "stack_size"
	// FieldAllowChunkMerge holds the string denoting the allow_chunk_merge field in the database.
	FieldAllowChunkMerge = "allow_chunk_merge"
	// FieldMaxChunkLength holds the string denoting the max_chunk_length field in the database.
	FieldMaxChunkLength = "max_chunk_length"
	// FieldMaxChunkJoinLength holds the string denoting the max_chunk_join_length field in the database.
	FieldMaxChunkJoinLength = "max_chunk_join_length"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeEntries holds the string denoting the entries edge name in mutations.
	EdgeEntries = "entries"
	// Table holds the table name of the list in the database.
	Table = "lists"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "lists"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_lists"
	// EntriesTable is the table that holds the entries relation/edge.
	EntriesTable = "list_entries"
	// EntriesInverseTable is the table name for the ListEntry entity.
	// It exists in this package in order to avoid circular dependency with the "listentry" package.
	EntriesInverseTable = "list_entries"
	// EntriesColumn is the table column denoting the entries relation/edge.
	EntriesColumn = "list_entries"
)

// Columns holds all SQL columns for list fields.
var Columns = []string{
	FieldID,
	FieldSynchronizedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldDescription,
	FieldStackSize,
	FieldAllowChunkMerge,
	FieldMaxChunkLength,
	FieldMaxChunkJoinLength,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "lists"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_lists",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStackSize holds the default value on creation for the "stack_size" field.
	DefaultStackSize uint
	// DefaultAllowChunkMerge holds the default value on creation for the "allow_chunk_merge" field.
	DefaultAllowChunkMerge bool
	// DefaultMaxChunkLength holds the default value on creation for the "max_chunk_length" field.
	DefaultMaxChunkLength uint
	// DefaultMaxChunkJoinLength holds the default value on creation for the "max_chunk_join_length" field.
	DefaultMaxChunkJoinLength uint
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the List queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySynchronizedAt orders the results by the synchronized_at field.
func BySynchronizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSynchronizedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStackSize orders the results by the stack_size field.
func ByStackSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStackSize, opts...).ToFunc()
}

// ByAllowChunkMerge orders the results by the allow_chunk_merge field.
func ByAllowChunkMerge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowChunkMerge, opts...).ToFunc()
}

// ByMaxChunkLength orders the results by the max_chunk_length field.
func ByMaxChunkLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxChunkLength, opts...).ToFunc()
}

// ByMaxChunkJoinLength orders the results by the max_chunk_join_length field.
func ByMaxChunkJoinLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxChunkJoinLength, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByEntriesCount orders the results by entries count.
func ByEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEntriesStep(), opts...)
	}
}

// ByEntries orders the results by entries terms.
func ByEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
	)
}
