// Code generated by ent, DO NOT EDIT.

package list

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"git.jojoxd.nl/projects/anistats/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.List {
	return predicate.List(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.List {
	return predicate.List(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.List {
	return predicate.List(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.List {
	return predicate.List(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.List {
	return predicate.List(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.List {
	return predicate.List(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.List {
	return predicate.List(sql.FieldLTE(FieldID, id))
}

// SynchronizedAt applies equality check predicate on the "synchronized_at" field. It's identical to SynchronizedAtEQ.
func SynchronizedAt(v time.Time) predicate.List {
	return predicate.List(sql.FieldEQ(FieldSynchronizedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.List {
	return predicate.List(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.List {
	return predicate.List(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.List {
	return predicate.List(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.List {
	return predicate.List(sql.FieldEQ(FieldDescription, v))
}

// StackSize applies equality check predicate on the "stack_size" field. It's identical to StackSizeEQ.
func StackSize(v uint) predicate.List {
	return predicate.List(sql.FieldEQ(FieldStackSize, v))
}

// AllowChunkMerge applies equality check predicate on the "allow_chunk_merge" field. It's identical to AllowChunkMergeEQ.
func AllowChunkMerge(v bool) predicate.List {
	return predicate.List(sql.FieldEQ(FieldAllowChunkMerge, v))
}

// MaxChunkLength applies equality check predicate on the "max_chunk_length" field. It's identical to MaxChunkLengthEQ.
func MaxChunkLength(v uint) predicate.List {
	return predicate.List(sql.FieldEQ(FieldMaxChunkLength, v))
}

// MaxChunkJoinLength applies equality check predicate on the "max_chunk_join_length" field. It's identical to MaxChunkJoinLengthEQ.
func MaxChunkJoinLength(v uint) predicate.List {
	return predicate.List(sql.FieldEQ(FieldMaxChunkJoinLength, v))
}

// SynchronizedAtEQ applies the EQ predicate on the "synchronized_at" field.
func SynchronizedAtEQ(v time.Time) predicate.List {
	return predicate.List(sql.FieldEQ(FieldSynchronizedAt, v))
}

// SynchronizedAtNEQ applies the NEQ predicate on the "synchronized_at" field.
func SynchronizedAtNEQ(v time.Time) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldSynchronizedAt, v))
}

// SynchronizedAtIn applies the In predicate on the "synchronized_at" field.
func SynchronizedAtIn(vs ...time.Time) predicate.List {
	return predicate.List(sql.FieldIn(FieldSynchronizedAt, vs...))
}

// SynchronizedAtNotIn applies the NotIn predicate on the "synchronized_at" field.
func SynchronizedAtNotIn(vs ...time.Time) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldSynchronizedAt, vs...))
}

// SynchronizedAtGT applies the GT predicate on the "synchronized_at" field.
func SynchronizedAtGT(v time.Time) predicate.List {
	return predicate.List(sql.FieldGT(FieldSynchronizedAt, v))
}

// SynchronizedAtGTE applies the GTE predicate on the "synchronized_at" field.
func SynchronizedAtGTE(v time.Time) predicate.List {
	return predicate.List(sql.FieldGTE(FieldSynchronizedAt, v))
}

// SynchronizedAtLT applies the LT predicate on the "synchronized_at" field.
func SynchronizedAtLT(v time.Time) predicate.List {
	return predicate.List(sql.FieldLT(FieldSynchronizedAt, v))
}

// SynchronizedAtLTE applies the LTE predicate on the "synchronized_at" field.
func SynchronizedAtLTE(v time.Time) predicate.List {
	return predicate.List(sql.FieldLTE(FieldSynchronizedAt, v))
}

// SynchronizedAtIsNil applies the IsNil predicate on the "synchronized_at" field.
func SynchronizedAtIsNil() predicate.List {
	return predicate.List(sql.FieldIsNull(FieldSynchronizedAt))
}

// SynchronizedAtNotNil applies the NotNil predicate on the "synchronized_at" field.
func SynchronizedAtNotNil() predicate.List {
	return predicate.List(sql.FieldNotNull(FieldSynchronizedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.List {
	return predicate.List(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.List {
	return predicate.List(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.List {
	return predicate.List(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.List {
	return predicate.List(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.List {
	return predicate.List(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.List {
	return predicate.List(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.List {
	return predicate.List(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.List {
	return predicate.List(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.List {
	return predicate.List(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.List {
	return predicate.List(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.List {
	return predicate.List(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.List {
	return predicate.List(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.List {
	return predicate.List(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.List {
	return predicate.List(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.List {
	return predicate.List(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.List {
	return predicate.List(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.List {
	return predicate.List(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.List {
	return predicate.List(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.List {
	return predicate.List(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.List {
	return predicate.List(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.List {
	return predicate.List(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.List {
	return predicate.List(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.List {
	return predicate.List(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.List {
	return predicate.List(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.List {
	return predicate.List(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.List {
	return predicate.List(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.List {
	return predicate.List(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.List {
	return predicate.List(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.List {
	return predicate.List(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.List {
	return predicate.List(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.List {
	return predicate.List(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.List {
	return predicate.List(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.List {
	return predicate.List(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.List {
	return predicate.List(sql.FieldContainsFold(FieldDescription, v))
}

// StackSizeEQ applies the EQ predicate on the "stack_size" field.
func StackSizeEQ(v uint) predicate.List {
	return predicate.List(sql.FieldEQ(FieldStackSize, v))
}

// StackSizeNEQ applies the NEQ predicate on the "stack_size" field.
func StackSizeNEQ(v uint) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldStackSize, v))
}

// StackSizeIn applies the In predicate on the "stack_size" field.
func StackSizeIn(vs ...uint) predicate.List {
	return predicate.List(sql.FieldIn(FieldStackSize, vs...))
}

// StackSizeNotIn applies the NotIn predicate on the "stack_size" field.
func StackSizeNotIn(vs ...uint) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldStackSize, vs...))
}

// StackSizeGT applies the GT predicate on the "stack_size" field.
func StackSizeGT(v uint) predicate.List {
	return predicate.List(sql.FieldGT(FieldStackSize, v))
}

// StackSizeGTE applies the GTE predicate on the "stack_size" field.
func StackSizeGTE(v uint) predicate.List {
	return predicate.List(sql.FieldGTE(FieldStackSize, v))
}

// StackSizeLT applies the LT predicate on the "stack_size" field.
func StackSizeLT(v uint) predicate.List {
	return predicate.List(sql.FieldLT(FieldStackSize, v))
}

// StackSizeLTE applies the LTE predicate on the "stack_size" field.
func StackSizeLTE(v uint) predicate.List {
	return predicate.List(sql.FieldLTE(FieldStackSize, v))
}

// AllowChunkMergeEQ applies the EQ predicate on the "allow_chunk_merge" field.
func AllowChunkMergeEQ(v bool) predicate.List {
	return predicate.List(sql.FieldEQ(FieldAllowChunkMerge, v))
}

// AllowChunkMergeNEQ applies the NEQ predicate on the "allow_chunk_merge" field.
func AllowChunkMergeNEQ(v bool) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldAllowChunkMerge, v))
}

// MaxChunkLengthEQ applies the EQ predicate on the "max_chunk_length" field.
func MaxChunkLengthEQ(v uint) predicate.List {
	return predicate.List(sql.FieldEQ(FieldMaxChunkLength, v))
}

// MaxChunkLengthNEQ applies the NEQ predicate on the "max_chunk_length" field.
func MaxChunkLengthNEQ(v uint) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldMaxChunkLength, v))
}

// MaxChunkLengthIn applies the In predicate on the "max_chunk_length" field.
func MaxChunkLengthIn(vs ...uint) predicate.List {
	return predicate.List(sql.FieldIn(FieldMaxChunkLength, vs...))
}

// MaxChunkLengthNotIn applies the NotIn predicate on the "max_chunk_length" field.
func MaxChunkLengthNotIn(vs ...uint) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldMaxChunkLength, vs...))
}

// MaxChunkLengthGT applies the GT predicate on the "max_chunk_length" field.
func MaxChunkLengthGT(v uint) predicate.List {
	return predicate.List(sql.FieldGT(FieldMaxChunkLength, v))
}

// MaxChunkLengthGTE applies the GTE predicate on the "max_chunk_length" field.
func MaxChunkLengthGTE(v uint) predicate.List {
	return predicate.List(sql.FieldGTE(FieldMaxChunkLength, v))
}

// MaxChunkLengthLT applies the LT predicate on the "max_chunk_length" field.
func MaxChunkLengthLT(v uint) predicate.List {
	return predicate.List(sql.FieldLT(FieldMaxChunkLength, v))
}

// MaxChunkLengthLTE applies the LTE predicate on the "max_chunk_length" field.
func MaxChunkLengthLTE(v uint) predicate.List {
	return predicate.List(sql.FieldLTE(FieldMaxChunkLength, v))
}

// MaxChunkJoinLengthEQ applies the EQ predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthEQ(v uint) predicate.List {
	return predicate.List(sql.FieldEQ(FieldMaxChunkJoinLength, v))
}

// MaxChunkJoinLengthNEQ applies the NEQ predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthNEQ(v uint) predicate.List {
	return predicate.List(sql.FieldNEQ(FieldMaxChunkJoinLength, v))
}

// MaxChunkJoinLengthIn applies the In predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthIn(vs ...uint) predicate.List {
	return predicate.List(sql.FieldIn(FieldMaxChunkJoinLength, vs...))
}

// MaxChunkJoinLengthNotIn applies the NotIn predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthNotIn(vs ...uint) predicate.List {
	return predicate.List(sql.FieldNotIn(FieldMaxChunkJoinLength, vs...))
}

// MaxChunkJoinLengthGT applies the GT predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthGT(v uint) predicate.List {
	return predicate.List(sql.FieldGT(FieldMaxChunkJoinLength, v))
}

// MaxChunkJoinLengthGTE applies the GTE predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthGTE(v uint) predicate.List {
	return predicate.List(sql.FieldGTE(FieldMaxChunkJoinLength, v))
}

// MaxChunkJoinLengthLT applies the LT predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthLT(v uint) predicate.List {
	return predicate.List(sql.FieldLT(FieldMaxChunkJoinLength, v))
}

// MaxChunkJoinLengthLTE applies the LTE predicate on the "max_chunk_join_length" field.
func MaxChunkJoinLengthLTE(v uint) predicate.List {
	return predicate.List(sql.FieldLTE(FieldMaxChunkJoinLength, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.List {
	return predicate.List(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.List {
	return predicate.List(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntries applies the HasEdge predicate on the "entries" edge.
func HasEntries() predicate.List {
	return predicate.List(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntriesWith applies the HasEdge predicate on the "entries" edge with a given conditions (other predicates).
func HasEntriesWith(preds ...predicate.ListEntry) predicate.List {
	return predicate.List(func(s *sql.Selector) {
		step := newEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.List) predicate.List {
	return predicate.List(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.List) predicate.List {
	return predicate.List(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.List) predicate.List {
	return predicate.List(sql.NotPredicates(p))
}
