// Code generated by ent, DO NOT EDIT.

package ent

import (
	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/predicate"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"git.jojoxd.nl/projects/anistats/backend/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 4)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   list.Table,
			Columns: list.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: list.FieldID,
			},
		},
		Type: "List",
		Fields: map[string]*sqlgraph.FieldSpec{
			list.FieldSynchronizedAt:     {Type: field.TypeTime, Column: list.FieldSynchronizedAt},
			list.FieldCreatedAt:          {Type: field.TypeTime, Column: list.FieldCreatedAt},
			list.FieldUpdatedAt:          {Type: field.TypeTime, Column: list.FieldUpdatedAt},
			list.FieldName:               {Type: field.TypeString, Column: list.FieldName},
			list.FieldDescription:        {Type: field.TypeString, Column: list.FieldDescription},
			list.FieldStackSize:          {Type: field.TypeUint, Column: list.FieldStackSize},
			list.FieldAllowChunkMerge:    {Type: field.TypeBool, Column: list.FieldAllowChunkMerge},
			list.FieldMaxChunkLength:     {Type: field.TypeUint, Column: list.FieldMaxChunkLength},
			list.FieldMaxChunkJoinLength: {Type: field.TypeUint, Column: list.FieldMaxChunkJoinLength},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   listentry.Table,
			Columns: listentry.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: listentry.FieldID,
			},
		},
		Type: "ListEntry",
		Fields: map[string]*sqlgraph.FieldSpec{
			listentry.FieldCreatedAt:        {Type: field.TypeTime, Column: listentry.FieldCreatedAt},
			listentry.FieldUpdatedAt:        {Type: field.TypeTime, Column: listentry.FieldUpdatedAt},
			listentry.FieldAnilistID:        {Type: field.TypeUint, Column: listentry.FieldAnilistID},
			listentry.FieldState:            {Type: field.TypeEnum, Column: listentry.FieldState},
			listentry.FieldProgress:         {Type: field.TypeUint, Column: listentry.FieldProgress},
			listentry.FieldMultiplier:       {Type: field.TypeFloat64, Column: listentry.FieldMultiplier},
			listentry.FieldOrder:            {Type: field.TypeUint, Column: listentry.FieldOrder},
			listentry.FieldStartAt:          {Type: field.TypeUint, Column: listentry.FieldStartAt},
			listentry.FieldSplit:            {Type: field.TypeUint, Column: listentry.FieldSplit},
			listentry.FieldSplitSequelEntry: {Type: field.TypeBool, Column: listentry.FieldSplitSequelEntry},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   series.Table,
			Columns: series.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: series.FieldID,
			},
		},
		Type: "Series",
		Fields: map[string]*sqlgraph.FieldSpec{
			series.FieldSynchronizedAt: {Type: field.TypeTime, Column: series.FieldSynchronizedAt},
			series.FieldCreatedAt:      {Type: field.TypeTime, Column: series.FieldCreatedAt},
			series.FieldUpdatedAt:      {Type: field.TypeTime, Column: series.FieldUpdatedAt},
			series.FieldAnilistID:      {Type: field.TypeUint, Column: series.FieldAnilistID},
			series.FieldTitleEnglish:   {Type: field.TypeString, Column: series.FieldTitleEnglish},
			series.FieldTitleNative:    {Type: field.TypeString, Column: series.FieldTitleNative},
			series.FieldTitleRomaji:    {Type: field.TypeString, Column: series.FieldTitleRomaji},
			series.FieldDescription:    {Type: field.TypeString, Column: series.FieldDescription},
			series.FieldCoverImageURL:  {Type: field.TypeString, Column: series.FieldCoverImageURL},
			series.FieldEpisodes:       {Type: field.TypeUint, Column: series.FieldEpisodes},
			series.FieldDuration:       {Type: field.TypeInt64, Column: series.FieldDuration},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: user.FieldID,
			},
		},
		Type: "User",
		Fields: map[string]*sqlgraph.FieldSpec{
			user.FieldSynchronizedAt: {Type: field.TypeTime, Column: user.FieldSynchronizedAt},
			user.FieldCreatedAt:      {Type: field.TypeTime, Column: user.FieldCreatedAt},
			user.FieldUpdatedAt:      {Type: field.TypeTime, Column: user.FieldUpdatedAt},
			user.FieldName:           {Type: field.TypeString, Column: user.FieldName},
			user.FieldAvatarURL:      {Type: field.TypeString, Column: user.FieldAvatarURL},
			user.FieldAnilistID:      {Type: field.TypeUint, Column: user.FieldAnilistID},
		},
	}
	graph.MustAddE(
		"owner",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   list.OwnerTable,
			Columns: []string{list.OwnerColumn},
			Bidi:    false,
		},
		"List",
		"User",
	)
	graph.MustAddE(
		"entries",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
		},
		"List",
		"ListEntry",
	)
	graph.MustAddE(
		"list",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listentry.ListTable,
			Columns: []string{listentry.ListColumn},
			Bidi:    false,
		},
		"ListEntry",
		"List",
	)
	graph.MustAddE(
		"series",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   listentry.SeriesTable,
			Columns: []string{listentry.SeriesColumn},
			Bidi:    false,
		},
		"ListEntry",
		"Series",
	)
	graph.MustAddE(
		"custom_sequel_series",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   listentry.CustomSequelSeriesTable,
			Columns: []string{listentry.CustomSequelSeriesColumn},
			Bidi:    false,
		},
		"ListEntry",
		"Series",
	)
	graph.MustAddE(
		"referenced_in",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
		},
		"Series",
		"ListEntry",
	)
	graph.MustAddE(
		"custom_sequel_of",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
		},
		"Series",
		"ListEntry",
	)
	graph.MustAddE(
		"prequels",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
		},
		"Series",
		"Series",
	)
	graph.MustAddE(
		"sequels",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
		},
		"Series",
		"Series",
	)
	graph.MustAddE(
		"lists",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListsTable,
			Columns: []string{user.ListsColumn},
			Bidi:    false,
		},
		"User",
		"List",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *ListQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ListQuery builder.
func (_q *ListQuery) Filter() *ListFilter {
	return &ListFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *ListMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ListMutation builder.
func (m *ListMutation) Filter() *ListFilter {
	return &ListFilter{config: m.config, predicateAdder: m}
}

// ListFilter provides a generic filtering capability at runtime for ListQuery.
type ListFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ListFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *ListFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(list.FieldID))
}

// WhereSynchronizedAt applies the entql time.Time predicate on the synchronized_at field.
func (f *ListFilter) WhereSynchronizedAt(p entql.TimeP) {
	f.Where(p.Field(list.FieldSynchronizedAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *ListFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(list.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *ListFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(list.FieldUpdatedAt))
}

// WhereName applies the entql string predicate on the name field.
func (f *ListFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(list.FieldName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *ListFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(list.FieldDescription))
}

// WhereStackSize applies the entql uint predicate on the stack_size field.
func (f *ListFilter) WhereStackSize(p entql.UintP) {
	f.Where(p.Field(list.FieldStackSize))
}

// WhereAllowChunkMerge applies the entql bool predicate on the allow_chunk_merge field.
func (f *ListFilter) WhereAllowChunkMerge(p entql.BoolP) {
	f.Where(p.Field(list.FieldAllowChunkMerge))
}

// WhereMaxChunkLength applies the entql uint predicate on the max_chunk_length field.
func (f *ListFilter) WhereMaxChunkLength(p entql.UintP) {
	f.Where(p.Field(list.FieldMaxChunkLength))
}

// WhereMaxChunkJoinLength applies the entql uint predicate on the max_chunk_join_length field.
func (f *ListFilter) WhereMaxChunkJoinLength(p entql.UintP) {
	f.Where(p.Field(list.FieldMaxChunkJoinLength))
}

// WhereHasOwner applies a predicate to check if query has an edge owner.
func (f *ListFilter) WhereHasOwner() {
	f.Where(entql.HasEdge("owner"))
}

// WhereHasOwnerWith applies a predicate to check if query has an edge owner with a given conditions (other predicates).
func (f *ListFilter) WhereHasOwnerWith(preds ...predicate.User) {
	f.Where(entql.HasEdgeWith("owner", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasEntries applies a predicate to check if query has an edge entries.
func (f *ListFilter) WhereHasEntries() {
	f.Where(entql.HasEdge("entries"))
}

// WhereHasEntriesWith applies a predicate to check if query has an edge entries with a given conditions (other predicates).
func (f *ListFilter) WhereHasEntriesWith(preds ...predicate.ListEntry) {
	f.Where(entql.HasEdgeWith("entries", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *ListEntryQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ListEntryQuery builder.
func (_q *ListEntryQuery) Filter() *ListEntryFilter {
	return &ListEntryFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *ListEntryMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ListEntryMutation builder.
func (m *ListEntryMutation) Filter() *ListEntryFilter {
	return &ListEntryFilter{config: m.config, predicateAdder: m}
}

// ListEntryFilter provides a generic filtering capability at runtime for ListEntryQuery.
type ListEntryFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ListEntryFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *ListEntryFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(listentry.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *ListEntryFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(listentry.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *ListEntryFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(listentry.FieldUpdatedAt))
}

// WhereAnilistID applies the entql uint predicate on the anilist_id field.
func (f *ListEntryFilter) WhereAnilistID(p entql.UintP) {
	f.Where(p.Field(listentry.FieldAnilistID))
}

// WhereState applies the entql string predicate on the state field.
func (f *ListEntryFilter) WhereState(p entql.StringP) {
	f.Where(p.Field(listentry.FieldState))
}

// WhereProgress applies the entql uint predicate on the progress field.
func (f *ListEntryFilter) WhereProgress(p entql.UintP) {
	f.Where(p.Field(listentry.FieldProgress))
}

// WhereMultiplier applies the entql float64 predicate on the multiplier field.
func (f *ListEntryFilter) WhereMultiplier(p entql.Float64P) {
	f.Where(p.Field(listentry.FieldMultiplier))
}

// WhereOrder applies the entql uint predicate on the order field.
func (f *ListEntryFilter) WhereOrder(p entql.UintP) {
	f.Where(p.Field(listentry.FieldOrder))
}

// WhereStartAt applies the entql uint predicate on the start_at field.
func (f *ListEntryFilter) WhereStartAt(p entql.UintP) {
	f.Where(p.Field(listentry.FieldStartAt))
}

// WhereSplit applies the entql uint predicate on the split field.
func (f *ListEntryFilter) WhereSplit(p entql.UintP) {
	f.Where(p.Field(listentry.FieldSplit))
}

// WhereSplitSequelEntry applies the entql bool predicate on the split_sequel_entry field.
func (f *ListEntryFilter) WhereSplitSequelEntry(p entql.BoolP) {
	f.Where(p.Field(listentry.FieldSplitSequelEntry))
}

// WhereHasList applies a predicate to check if query has an edge list.
func (f *ListEntryFilter) WhereHasList() {
	f.Where(entql.HasEdge("list"))
}

// WhereHasListWith applies a predicate to check if query has an edge list with a given conditions (other predicates).
func (f *ListEntryFilter) WhereHasListWith(preds ...predicate.List) {
	f.Where(entql.HasEdgeWith("list", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasSeries applies a predicate to check if query has an edge series.
func (f *ListEntryFilter) WhereHasSeries() {
	f.Where(entql.HasEdge("series"))
}

// WhereHasSeriesWith applies a predicate to check if query has an edge series with a given conditions (other predicates).
func (f *ListEntryFilter) WhereHasSeriesWith(preds ...predicate.Series) {
	f.Where(entql.HasEdgeWith("series", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasCustomSequelSeries applies a predicate to check if query has an edge custom_sequel_series.
func (f *ListEntryFilter) WhereHasCustomSequelSeries() {
	f.Where(entql.HasEdge("custom_sequel_series"))
}

// WhereHasCustomSequelSeriesWith applies a predicate to check if query has an edge custom_sequel_series with a given conditions (other predicates).
func (f *ListEntryFilter) WhereHasCustomSequelSeriesWith(preds ...predicate.Series) {
	f.Where(entql.HasEdgeWith("custom_sequel_series", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *SeriesQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SeriesQuery builder.
func (_q *SeriesQuery) Filter() *SeriesFilter {
	return &SeriesFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *SeriesMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SeriesMutation builder.
func (m *SeriesMutation) Filter() *SeriesFilter {
	return &SeriesFilter{config: m.config, predicateAdder: m}
}

// SeriesFilter provides a generic filtering capability at runtime for SeriesQuery.
type SeriesFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SeriesFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *SeriesFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(series.FieldID))
}

// WhereSynchronizedAt applies the entql time.Time predicate on the synchronized_at field.
func (f *SeriesFilter) WhereSynchronizedAt(p entql.TimeP) {
	f.Where(p.Field(series.FieldSynchronizedAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *SeriesFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(series.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *SeriesFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(series.FieldUpdatedAt))
}

// WhereAnilistID applies the entql uint predicate on the anilist_id field.
func (f *SeriesFilter) WhereAnilistID(p entql.UintP) {
	f.Where(p.Field(series.FieldAnilistID))
}

// WhereTitleEnglish applies the entql string predicate on the title_english field.
func (f *SeriesFilter) WhereTitleEnglish(p entql.StringP) {
	f.Where(p.Field(series.FieldTitleEnglish))
}

// WhereTitleNative applies the entql string predicate on the title_native field.
func (f *SeriesFilter) WhereTitleNative(p entql.StringP) {
	f.Where(p.Field(series.FieldTitleNative))
}

// WhereTitleRomaji applies the entql string predicate on the title_romaji field.
func (f *SeriesFilter) WhereTitleRomaji(p entql.StringP) {
	f.Where(p.Field(series.FieldTitleRomaji))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *SeriesFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(series.FieldDescription))
}

// WhereCoverImageURL applies the entql string predicate on the cover_image_url field.
func (f *SeriesFilter) WhereCoverImageURL(p entql.StringP) {
	f.Where(p.Field(series.FieldCoverImageURL))
}

// WhereEpisodes applies the entql uint predicate on the episodes field.
func (f *SeriesFilter) WhereEpisodes(p entql.UintP) {
	f.Where(p.Field(series.FieldEpisodes))
}

// WhereDuration applies the entql int64 predicate on the duration field.
func (f *SeriesFilter) WhereDuration(p entql.Int64P) {
	f.Where(p.Field(series.FieldDuration))
}

// WhereHasReferencedIn applies a predicate to check if query has an edge referenced_in.
func (f *SeriesFilter) WhereHasReferencedIn() {
	f.Where(entql.HasEdge("referenced_in"))
}

// WhereHasReferencedInWith applies a predicate to check if query has an edge referenced_in with a given conditions (other predicates).
func (f *SeriesFilter) WhereHasReferencedInWith(preds ...predicate.ListEntry) {
	f.Where(entql.HasEdgeWith("referenced_in", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasCustomSequelOf applies a predicate to check if query has an edge custom_sequel_of.
func (f *SeriesFilter) WhereHasCustomSequelOf() {
	f.Where(entql.HasEdge("custom_sequel_of"))
}

// WhereHasCustomSequelOfWith applies a predicate to check if query has an edge custom_sequel_of with a given conditions (other predicates).
func (f *SeriesFilter) WhereHasCustomSequelOfWith(preds ...predicate.ListEntry) {
	f.Where(entql.HasEdgeWith("custom_sequel_of", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasPrequels applies a predicate to check if query has an edge prequels.
func (f *SeriesFilter) WhereHasPrequels() {
	f.Where(entql.HasEdge("prequels"))
}

// WhereHasPrequelsWith applies a predicate to check if query has an edge prequels with a given conditions (other predicates).
func (f *SeriesFilter) WhereHasPrequelsWith(preds ...predicate.Series) {
	f.Where(entql.HasEdgeWith("prequels", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasSequels applies a predicate to check if query has an edge sequels.
func (f *SeriesFilter) WhereHasSequels() {
	f.Where(entql.HasEdge("sequels"))
}

// WhereHasSequelsWith applies a predicate to check if query has an edge sequels with a given conditions (other predicates).
func (f *SeriesFilter) WhereHasSequelsWith(preds ...predicate.Series) {
	f.Where(entql.HasEdgeWith("sequels", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *UserQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the UserQuery builder.
func (_q *UserQuery) Filter() *UserFilter {
	return &UserFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *UserMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the UserMutation builder.
func (m *UserMutation) Filter() *UserFilter {
	return &UserFilter{config: m.config, predicateAdder: m}
}

// UserFilter provides a generic filtering capability at runtime for UserQuery.
type UserFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *UserFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *UserFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(user.FieldID))
}

// WhereSynchronizedAt applies the entql time.Time predicate on the synchronized_at field.
func (f *UserFilter) WhereSynchronizedAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldSynchronizedAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *UserFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *UserFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldUpdatedAt))
}

// WhereName applies the entql string predicate on the name field.
func (f *UserFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(user.FieldName))
}

// WhereAvatarURL applies the entql string predicate on the avatar_url field.
func (f *UserFilter) WhereAvatarURL(p entql.StringP) {
	f.Where(p.Field(user.FieldAvatarURL))
}

// WhereAnilistID applies the entql uint predicate on the anilist_id field.
func (f *UserFilter) WhereAnilistID(p entql.UintP) {
	f.Where(p.Field(user.FieldAnilistID))
}

// WhereHasLists applies a predicate to check if query has an edge lists.
func (f *UserFilter) WhereHasLists() {
	f.Where(entql.HasEdge("lists"))
}

// WhereHasListsWith applies a predicate to check if query has an edge lists with a given conditions (other predicates).
func (f *UserFilter) WhereHasListsWith(preds ...predicate.List) {
	f.Where(entql.HasEdgeWith("lists", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
