// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.jojoxd.nl/projects/anistats/backend/api"
	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"github.com/google/uuid"
)

// ListEntryCreate is the builder for creating a ListEntry entity.
type ListEntryCreate struct {
	config
	mutation *ListEntryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ListEntryCreate) SetCreatedAt(v time.Time) *ListEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableCreatedAt(v *time.Time) *ListEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ListEntryCreate) SetUpdatedAt(v time.Time) *ListEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableUpdatedAt(v *time.Time) *ListEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAnilistID sets the "anilist_id" field.
func (_c *ListEntryCreate) SetAnilistID(v uint) *ListEntryCreate {
	_c.mutation.SetAnilistID(v)
	return _c
}

// SetState sets the "state" field.
func (_c *ListEntryCreate) SetState(v api.EntryStatus) *ListEntryCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetProgress sets the "progress" field.
func (_c *ListEntryCreate) SetProgress(v uint) *ListEntryCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableProgress(v *uint) *ListEntryCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetMultiplier sets the "multiplier" field.
func (_c *ListEntryCreate) SetMultiplier(v float64) *ListEntryCreate {
	_c.mutation.SetMultiplier(v)
	return _c
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableMultiplier(v *float64) *ListEntryCreate {
	if v != nil {
		_c.SetMultiplier(*v)
	}
	return _c
}

// SetOrder sets the "order" field.
func (_c *ListEntryCreate) SetOrder(v uint) *ListEntryCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableOrder(v *uint) *ListEntryCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *ListEntryCreate) SetStartAt(v uint) *ListEntryCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableStartAt(v *uint) *ListEntryCreate {
	if v != nil {
		_c.SetStartAt(*v)
	}
	return _c
}

// SetSplit sets the "split" field.
func (_c *ListEntryCreate) SetSplit(v uint) *ListEntryCreate {
	_c.mutation.SetSplit(v)
	return _c
}

// SetNillableSplit sets the "split" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableSplit(v *uint) *ListEntryCreate {
	if v != nil {
		_c.SetSplit(*v)
	}
	return _c
}

// SetSplitSequelEntry sets the "split_sequel_entry" field.
func (_c *ListEntryCreate) SetSplitSequelEntry(v bool) *ListEntryCreate {
	_c.mutation.SetSplitSequelEntry(v)
	return _c
}

// SetNillableSplitSequelEntry sets the "split_sequel_entry" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableSplitSequelEntry(v *bool) *ListEntryCreate {
	if v != nil {
		_c.SetSplitSequelEntry(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ListEntryCreate) SetID(v uuid.UUID) *ListEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ListEntryCreate) SetNillableID(v *uuid.UUID) *ListEntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetListID sets the "list" edge to the List entity by ID.
func (_c *ListEntryCreate) SetListID(id uuid.UUID) *ListEntryCreate {
	_c.mutation.SetListID(id)
	return _c
}

// SetNillableListID sets the "list" edge to the List entity by ID if the given value is not nil.
func (_c *ListEntryCreate) SetNillableListID(id *uuid.UUID) *ListEntryCreate {
	if id != nil {
		_c = _c.SetListID(*id)
	}
	return _c
}

// SetList sets the "list" edge to the List entity.
func (_c *ListEntryCreate) SetList(v *List) *ListEntryCreate {
	return _c.SetListID(v.ID)
}

// SetSeriesID sets the "series" edge to the Series entity by ID.
func (_c *ListEntryCreate) SetSeriesID(id uuid.UUID) *ListEntryCreate {
	_c.mutation.SetSeriesID(id)
	return _c
}

// SetNillableSeriesID sets the "series" edge to the Series entity by ID if the given value is not nil.
func (_c *ListEntryCreate) SetNillableSeriesID(id *uuid.UUID) *ListEntryCreate {
	if id != nil {
		_c = _c.SetSeriesID(*id)
	}
	return _c
}

// SetSeries sets the "series" edge to the Series entity.
func (_c *ListEntryCreate) SetSeries(v *Series) *ListEntryCreate {
	return _c.SetSeriesID(v.ID)
}

// SetCustomSequelSeriesID sets the "custom_sequel_series" edge to the Series entity by ID.
func (_c *ListEntryCreate) SetCustomSequelSeriesID(id uuid.UUID) *ListEntryCreate {
	_c.mutation.SetCustomSequelSeriesID(id)
	return _c
}

// SetNillableCustomSequelSeriesID sets the "custom_sequel_series" edge to the Series entity by ID if the given value is not nil.
func (_c *ListEntryCreate) SetNillableCustomSequelSeriesID(id *uuid.UUID) *ListEntryCreate {
	if id != nil {
		_c = _c.SetCustomSequelSeriesID(*id)
	}
	return _c
}

// SetCustomSequelSeries sets the "custom_sequel_series" edge to the Series entity.
func (_c *ListEntryCreate) SetCustomSequelSeries(v *Series) *ListEntryCreate {
	return _c.SetCustomSequelSeriesID(v.ID)
}

// Mutation returns the ListEntryMutation object of the builder.
func (_c *ListEntryCreate) Mutation() *ListEntryMutation {
	return _c.mutation
}

// Save creates the ListEntry in the database.
func (_c *ListEntryCreate) Save(ctx context.Context) (*ListEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListEntryCreate) SaveX(ctx context.Context) *ListEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListEntryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := listentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := listentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := listentry.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.Multiplier(); !ok {
		v := listentry.DefaultMultiplier
		_c.mutation.SetMultiplier(v)
	}
	if _, ok := _c.mutation.SplitSequelEntry(); !ok {
		v := listentry.DefaultSplitSequelEntry
		_c.mutation.SetSplitSequelEntry(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := listentry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListEntryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ListEntry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ListEntry.updated_at"`)}
	}
	if _, ok := _c.mutation.AnilistID(); !ok {
		return &ValidationError{Name: "anilist_id", err: errors.New(`ent: missing required field "ListEntry.anilist_id"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "ListEntry.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := listentry.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ListEntry.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "ListEntry.progress"`)}
	}
	if _, ok := _c.mutation.Multiplier(); !ok {
		return &ValidationError{Name: "multiplier", err: errors.New(`ent: missing required field "ListEntry.multiplier"`)}
	}
	if _, ok := _c.mutation.SplitSequelEntry(); !ok {
		return &ValidationError{Name: "split_sequel_entry", err: errors.New(`ent: missing required field "ListEntry.split_sequel_entry"`)}
	}
	return nil
}

func (_c *ListEntryCreate) sqlSave(ctx context.Context) (*ListEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListEntryCreate) createSpec() (*ListEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &ListEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(listentry.Table, sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(listentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(listentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AnilistID(); ok {
		_spec.SetField(listentry.FieldAnilistID, field.TypeUint, value)
		_node.AnilistID = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(listentry.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(listentry.FieldProgress, field.TypeUint, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.Multiplier(); ok {
		_spec.SetField(listentry.FieldMultiplier, field.TypeFloat64, value)
		_node.Multiplier = value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(listentry.FieldOrder, field.TypeUint, value)
		_node.Order = &value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(listentry.FieldStartAt, field.TypeUint, value)
		_node.StartAt = &value
	}
	if value, ok := _c.mutation.Split(); ok {
		_spec.SetField(listentry.FieldSplit, field.TypeUint, value)
		_node.Split = &value
	}
	if value, ok := _c.mutation.SplitSequelEntry(); ok {
		_spec.SetField(listentry.FieldSplitSequelEntry, field.TypeBool, value)
		_node.SplitSequelEntry = value
	}
	if nodes := _c.mutation.ListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listentry.ListTable,
			Columns: []string{listentry.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(list.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.list_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   listentry.SeriesTable,
			Columns: []string{listentry.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.list_entry_series = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomSequelSeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   listentry.CustomSequelSeriesTable,
			Columns: []string{listentry.CustomSequelSeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.list_entry_custom_sequel_series = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ListEntryCreateBulk is the builder for creating many ListEntry entities in bulk.
type ListEntryCreateBulk struct {
	config
	err      error
	builders []*ListEntryCreate
}

// Save creates the ListEntry entities in the database.
func (_c *ListEntryCreateBulk) Save(ctx context.Context) ([]*ListEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ListEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListEntryCreateBulk) SaveX(ctx context.Context) []*ListEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
