// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/predicate"
	"git.jojoxd.nl/projects/anistats/backend/ent/user"
	"github.com/google/uuid"
)

// ListUpdate is the builder for updating List entities.
type ListUpdate struct {
	config
	hooks    []Hook
	mutation *ListMutation
}

// Where appends a list predicates to the ListUpdate builder.
func (_u *ListUpdate) Where(ps ...predicate.List) *ListUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSynchronizedAt sets the "synchronized_at" field.
func (_u *ListUpdate) SetSynchronizedAt(v time.Time) *ListUpdate {
	_u.mutation.SetSynchronizedAt(v)
	return _u
}

// SetNillableSynchronizedAt sets the "synchronized_at" field if the given value is not nil.
func (_u *ListUpdate) SetNillableSynchronizedAt(v *time.Time) *ListUpdate {
	if v != nil {
		_u.SetSynchronizedAt(*v)
	}
	return _u
}

// ClearSynchronizedAt clears the value of the "synchronized_at" field.
func (_u *ListUpdate) ClearSynchronizedAt() *ListUpdate {
	_u.mutation.ClearSynchronizedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ListUpdate) SetUpdatedAt(v time.Time) *ListUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ListUpdate) SetName(v string) *ListUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ListUpdate) SetNillableName(v *string) *ListUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ListUpdate) SetDescription(v string) *ListUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ListUpdate) SetNillableDescription(v *string) *ListUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStackSize sets the "stack_size" field.
func (_u *ListUpdate) SetStackSize(v uint) *ListUpdate {
	_u.mutation.ResetStackSize()
	_u.mutation.SetStackSize(v)
	return _u
}

// SetNillableStackSize sets the "stack_size" field if the given value is not nil.
func (_u *ListUpdate) SetNillableStackSize(v *uint) *ListUpdate {
	if v != nil {
		_u.SetStackSize(*v)
	}
	return _u
}

// AddStackSize adds value to the "stack_size" field.
func (_u *ListUpdate) AddStackSize(v int) *ListUpdate {
	_u.mutation.AddStackSize(v)
	return _u
}

// SetAllowChunkMerge sets the "allow_chunk_merge" field.
func (_u *ListUpdate) SetAllowChunkMerge(v bool) *ListUpdate {
	_u.mutation.SetAllowChunkMerge(v)
	return _u
}

// SetNillableAllowChunkMerge sets the "allow_chunk_merge" field if the given value is not nil.
func (_u *ListUpdate) SetNillableAllowChunkMerge(v *bool) *ListUpdate {
	if v != nil {
		_u.SetAllowChunkMerge(*v)
	}
	return _u
}

// SetMaxChunkLength sets the "max_chunk_length" field.
func (_u *ListUpdate) SetMaxChunkLength(v uint) *ListUpdate {
	_u.mutation.ResetMaxChunkLength()
	_u.mutation.SetMaxChunkLength(v)
	return _u
}

// SetNillableMaxChunkLength sets the "max_chunk_length" field if the given value is not nil.
func (_u *ListUpdate) SetNillableMaxChunkLength(v *uint) *ListUpdate {
	if v != nil {
		_u.SetMaxChunkLength(*v)
	}
	return _u
}

// AddMaxChunkLength adds value to the "max_chunk_length" field.
func (_u *ListUpdate) AddMaxChunkLength(v int) *ListUpdate {
	_u.mutation.AddMaxChunkLength(v)
	return _u
}

// SetMaxChunkJoinLength sets the "max_chunk_join_length" field.
func (_u *ListUpdate) SetMaxChunkJoinLength(v uint) *ListUpdate {
	_u.mutation.ResetMaxChunkJoinLength()
	_u.mutation.SetMaxChunkJoinLength(v)
	return _u
}

// SetNillableMaxChunkJoinLength sets the "max_chunk_join_length" field if the given value is not nil.
func (_u *ListUpdate) SetNillableMaxChunkJoinLength(v *uint) *ListUpdate {
	if v != nil {
		_u.SetMaxChunkJoinLength(*v)
	}
	return _u
}

// AddMaxChunkJoinLength adds value to the "max_chunk_join_length" field.
func (_u *ListUpdate) AddMaxChunkJoinLength(v int) *ListUpdate {
	_u.mutation.AddMaxChunkJoinLength(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ListUpdate) SetOwnerID(id uuid.UUID) *ListUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ListUpdate) SetNillableOwnerID(id *uuid.UUID) *ListUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ListUpdate) SetOwner(v *User) *ListUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the ListEntry entity by IDs.
func (_u *ListUpdate) AddEntryIDs(ids ...uuid.UUID) *ListUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the ListEntry entity.
func (_u *ListUpdate) AddEntries(v ...*ListEntry) *ListUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the ListMutation object of the builder.
func (_u *ListUpdate) Mutation() *ListMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ListUpdate) ClearOwner() *ListUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearEntries clears all "entries" edges to the ListEntry entity.
func (_u *ListUpdate) ClearEntries() *ListUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to ListEntry entities by IDs.
func (_u *ListUpdate) RemoveEntryIDs(ids ...uuid.UUID) *ListUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to ListEntry entities.
func (_u *ListUpdate) RemoveEntries(v ...*ListEntry) *ListUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ListUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ListUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ListUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := list.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ListUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(list.Table, list.Columns, sqlgraph.NewFieldSpec(list.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SynchronizedAt(); ok {
		_spec.SetField(list.FieldSynchronizedAt, field.TypeTime, value)
	}
	if _u.mutation.SynchronizedAtCleared() {
		_spec.ClearField(list.FieldSynchronizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(list.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(list.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(list.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.StackSize(); ok {
		_spec.SetField(list.FieldStackSize, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedStackSize(); ok {
		_spec.AddField(list.FieldStackSize, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AllowChunkMerge(); ok {
		_spec.SetField(list.FieldAllowChunkMerge, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxChunkLength(); ok {
		_spec.SetField(list.FieldMaxChunkLength, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedMaxChunkLength(); ok {
		_spec.AddField(list.FieldMaxChunkLength, field.TypeUint, value)
	}
	if value, ok := _u.mutation.MaxChunkJoinLength(); ok {
		_spec.SetField(list.FieldMaxChunkJoinLength, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedMaxChunkJoinLength(); ok {
		_spec.AddField(list.FieldMaxChunkJoinLength, field.TypeUint, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   list.OwnerTable,
			Columns: []string{list.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   list.OwnerTable,
			Columns: []string{list.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{list.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ListUpdateOne is the builder for updating a single List entity.
type ListUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ListMutation
}

// SetSynchronizedAt sets the "synchronized_at" field.
func (_u *ListUpdateOne) SetSynchronizedAt(v time.Time) *ListUpdateOne {
	_u.mutation.SetSynchronizedAt(v)
	return _u
}

// SetNillableSynchronizedAt sets the "synchronized_at" field if the given value is not nil.
func (_u *ListUpdateOne) SetNillableSynchronizedAt(v *time.Time) *ListUpdateOne {
	if v != nil {
		_u.SetSynchronizedAt(*v)
	}
	return _u
}

// ClearSynchronizedAt clears the value of the "synchronized_at" field.
func (_u *ListUpdateOne) ClearSynchronizedAt() *ListUpdateOne {
	_u.mutation.ClearSynchronizedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ListUpdateOne) SetUpdatedAt(v time.Time) *ListUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ListUpdateOne) SetName(v string) *ListUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ListUpdateOne) SetNillableName(v *string) *ListUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ListUpdateOne) SetDescription(v string) *ListUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ListUpdateOne) SetNillableDescription(v *string) *ListUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStackSize sets the "stack_size" field.
func (_u *ListUpdateOne) SetStackSize(v uint) *ListUpdateOne {
	_u.mutation.ResetStackSize()
	_u.mutation.SetStackSize(v)
	return _u
}

// SetNillableStackSize sets the "stack_size" field if the given value is not nil.
func (_u *ListUpdateOne) SetNillableStackSize(v *uint) *ListUpdateOne {
	if v != nil {
		_u.SetStackSize(*v)
	}
	return _u
}

// AddStackSize adds value to the "stack_size" field.
func (_u *ListUpdateOne) AddStackSize(v int) *ListUpdateOne {
	_u.mutation.AddStackSize(v)
	return _u
}

// SetAllowChunkMerge sets the "allow_chunk_merge" field.
func (_u *ListUpdateOne) SetAllowChunkMerge(v bool) *ListUpdateOne {
	_u.mutation.SetAllowChunkMerge(v)
	return _u
}

// SetNillableAllowChunkMerge sets the "allow_chunk_merge" field if the given value is not nil.
func (_u *ListUpdateOne) SetNillableAllowChunkMerge(v *bool) *ListUpdateOne {
	if v != nil {
		_u.SetAllowChunkMerge(*v)
	}
	return _u
}

// SetMaxChunkLength sets the "max_chunk_length" field.
func (_u *ListUpdateOne) SetMaxChunkLength(v uint) *ListUpdateOne {
	_u.mutation.ResetMaxChunkLength()
	_u.mutation.SetMaxChunkLength(v)
	return _u
}

// SetNillableMaxChunkLength sets the "max_chunk_length" field if the given value is not nil.
func (_u *ListUpdateOne) SetNillableMaxChunkLength(v *uint) *ListUpdateOne {
	if v != nil {
		_u.SetMaxChunkLength(*v)
	}
	return _u
}

// AddMaxChunkLength adds value to the "max_chunk_length" field.
func (_u *ListUpdateOne) AddMaxChunkLength(v int) *ListUpdateOne {
	_u.mutation.AddMaxChunkLength(v)
	return _u
}

// SetMaxChunkJoinLength sets the "max_chunk_join_length" field.
func (_u *ListUpdateOne) SetMaxChunkJoinLength(v uint) *ListUpdateOne {
	_u.mutation.ResetMaxChunkJoinLength()
	_u.mutation.SetMaxChunkJoinLength(v)
	return _u
}

// SetNillableMaxChunkJoinLength sets the "max_chunk_join_length" field if the given value is not nil.
func (_u *ListUpdateOne) SetNillableMaxChunkJoinLength(v *uint) *ListUpdateOne {
	if v != nil {
		_u.SetMaxChunkJoinLength(*v)
	}
	return _u
}

// AddMaxChunkJoinLength adds value to the "max_chunk_join_length" field.
func (_u *ListUpdateOne) AddMaxChunkJoinLength(v int) *ListUpdateOne {
	_u.mutation.AddMaxChunkJoinLength(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ListUpdateOne) SetOwnerID(id uuid.UUID) *ListUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ListUpdateOne) SetNillableOwnerID(id *uuid.UUID) *ListUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ListUpdateOne) SetOwner(v *User) *ListUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the ListEntry entity by IDs.
func (_u *ListUpdateOne) AddEntryIDs(ids ...uuid.UUID) *ListUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the ListEntry entity.
func (_u *ListUpdateOne) AddEntries(v ...*ListEntry) *ListUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the ListMutation object of the builder.
func (_u *ListUpdateOne) Mutation() *ListMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ListUpdateOne) ClearOwner() *ListUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearEntries clears all "entries" edges to the ListEntry entity.
func (_u *ListUpdateOne) ClearEntries() *ListUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to ListEntry entities by IDs.
func (_u *ListUpdateOne) RemoveEntryIDs(ids ...uuid.UUID) *ListUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to ListEntry entities.
func (_u *ListUpdateOne) RemoveEntries(v ...*ListEntry) *ListUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Where appends a list predicates to the ListUpdate builder.
func (_u *ListUpdateOne) Where(ps ...predicate.List) *ListUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ListUpdateOne) Select(field string, fields ...string) *ListUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated List entity.
func (_u *ListUpdateOne) Save(ctx context.Context) (*List, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListUpdateOne) SaveX(ctx context.Context) *List {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ListUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ListUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := list.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ListUpdateOne) sqlSave(ctx context.Context) (_node *List, err error) {
	_spec := sqlgraph.NewUpdateSpec(list.Table, list.Columns, sqlgraph.NewFieldSpec(list.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "List.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, list.FieldID)
		for _, f := range fields {
			if !list.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != list.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SynchronizedAt(); ok {
		_spec.SetField(list.FieldSynchronizedAt, field.TypeTime, value)
	}
	if _u.mutation.SynchronizedAtCleared() {
		_spec.ClearField(list.FieldSynchronizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(list.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(list.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(list.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.StackSize(); ok {
		_spec.SetField(list.FieldStackSize, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedStackSize(); ok {
		_spec.AddField(list.FieldStackSize, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AllowChunkMerge(); ok {
		_spec.SetField(list.FieldAllowChunkMerge, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxChunkLength(); ok {
		_spec.SetField(list.FieldMaxChunkLength, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedMaxChunkLength(); ok {
		_spec.AddField(list.FieldMaxChunkLength, field.TypeUint, value)
	}
	if value, ok := _u.mutation.MaxChunkJoinLength(); ok {
		_spec.SetField(list.FieldMaxChunkJoinLength, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedMaxChunkJoinLength(); ok {
		_spec.AddField(list.FieldMaxChunkJoinLength, field.TypeUint, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   list.OwnerTable,
			Columns: []string{list.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   list.OwnerTable,
			Columns: []string{list.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &List{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{list.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
