// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"git.jojoxd.nl/projects/anistats/backend/api"
	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"github.com/google/uuid"
)

// ListEntry is the model entity for the ListEntry schema.
type ListEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AnilistID holds the value of the "anilist_id" field.
	AnilistID uint `json:"anilist_id,omitempty"`
	// State holds the value of the "state" field.
	State api.EntryStatus `json:"state,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress uint `json:"progress,omitempty"`
	// Multiplier holds the value of the "multiplier" field.
	Multiplier float64 `json:"multiplier,omitempty"`
	// Order holds the value of the "order" field.
	Order *uint `json:"order,omitempty"`
	// StartAt holds the value of the "start_at" field.
	StartAt *uint `json:"start_at,omitempty"`
	// Split holds the value of the "split" field.
	Split *uint `json:"split,omitempty"`
	// SplitSequelEntry holds the value of the "split_sequel_entry" field.
	SplitSequelEntry bool `json:"split_sequel_entry,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ListEntryQuery when eager-loading is set.
	Edges                           ListEntryEdges `json:"edges"`
	list_entries                    *uuid.UUID
	list_entry_series               *uuid.UUID
	list_entry_custom_sequel_series *uuid.UUID
	selectValues                    sql.SelectValues
}

// ListEntryEdges holds the relations/edges for other nodes in the graph.
type ListEntryEdges struct {
	// List holds the value of the list edge.
	List *List `json:"list,omitempty"`
	// Series holds the value of the series edge.
	Series *Series `json:"series,omitempty"`
	// CustomSequelSeries holds the value of the custom_sequel_series edge.
	CustomSequelSeries *Series `json:"custom_sequel_series,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ListOrErr returns the List value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListEntryEdges) ListOrErr() (*List, error) {
	if e.List != nil {
		return e.List, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: list.Label}
	}
	return nil, &NotLoadedError{edge: "list"}
}

// SeriesOrErr returns the Series value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListEntryEdges) SeriesOrErr() (*Series, error) {
	if e.Series != nil {
		return e.Series, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: series.Label}
	}
	return nil, &NotLoadedError{edge: "series"}
}

// CustomSequelSeriesOrErr returns the CustomSequelSeries value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListEntryEdges) CustomSequelSeriesOrErr() (*Series, error) {
	if e.CustomSequelSeries != nil {
		return e.CustomSequelSeries, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: series.Label}
	}
	return nil, &NotLoadedError{edge: "custom_sequel_series"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ListEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case listentry.FieldSplitSequelEntry:
			values[i] = new(sql.NullBool)
		case listentry.FieldMultiplier:
			values[i] = new(sql.NullFloat64)
		case listentry.FieldAnilistID, listentry.FieldProgress, listentry.FieldOrder, listentry.FieldStartAt, listentry.FieldSplit:
			values[i] = new(sql.NullInt64)
		case listentry.FieldState:
			values[i] = new(sql.NullString)
		case listentry.FieldCreatedAt, listentry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case listentry.FieldID:
			values[i] = new(uuid.UUID)
		case listentry.ForeignKeys[0]: // list_entries
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case listentry.ForeignKeys[1]: // list_entry_series
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case listentry.ForeignKeys[2]: // list_entry_custom_sequel_series
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ListEntry fields.
func (_m *ListEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case listentry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case listentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case listentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case listentry.FieldAnilistID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field anilist_id", values[i])
			} else if value.Valid {
				_m.AnilistID = uint(value.Int64)
			}
		case listentry.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = api.EntryStatus(value.String)
			}
		case listentry.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = uint(value.Int64)
			}
		case listentry.FieldMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field multiplier", values[i])
			} else if value.Valid {
				_m.Multiplier = value.Float64
			}
		case listentry.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				_m.Order = new(uint)
				*_m.Order = uint(value.Int64)
			}
		case listentry.FieldStartAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_at", values[i])
			} else if value.Valid {
				_m.StartAt = new(uint)
				*_m.StartAt = uint(value.Int64)
			}
		case listentry.FieldSplit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field split", values[i])
			} else if value.Valid {
				_m.Split = new(uint)
				*_m.Split = uint(value.Int64)
			}
		case listentry.FieldSplitSequelEntry:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field split_sequel_entry", values[i])
			} else if value.Valid {
				_m.SplitSequelEntry = value.Bool
			}
		case listentry.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field list_entries", values[i])
			} else if value.Valid {
				_m.list_entries = new(uuid.UUID)
				*_m.list_entries = *value.S.(*uuid.UUID)
			}
		case listentry.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field list_entry_series", values[i])
			} else if value.Valid {
				_m.list_entry_series = new(uuid.UUID)
				*_m.list_entry_series = *value.S.(*uuid.UUID)
			}
		case listentry.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field list_entry_custom_sequel_series", values[i])
			} else if value.Valid {
				_m.list_entry_custom_sequel_series = new(uuid.UUID)
				*_m.list_entry_custom_sequel_series = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ListEntry.
// This includes values selected through modifiers, order, etc.
func (_m *ListEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryList queries the "list" edge of the ListEntry entity.
func (_m *ListEntry) QueryList() *ListQuery {
	return NewListEntryClient(_m.config).QueryList(_m)
}

// QuerySeries queries the "series" edge of the ListEntry entity.
func (_m *ListEntry) QuerySeries() *SeriesQuery {
	return NewListEntryClient(_m.config).QuerySeries(_m)
}

// QueryCustomSequelSeries queries the "custom_sequel_series" edge of the ListEntry entity.
func (_m *ListEntry) QueryCustomSequelSeries() *SeriesQuery {
	return NewListEntryClient(_m.config).QueryCustomSequelSeries(_m)
}

// Update returns a builder for updating this ListEntry.
// Note that you need to call ListEntry.Unwrap() before calling this method if this ListEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ListEntry) Update() *ListEntryUpdateOne {
	return NewListEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ListEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ListEntry) Unwrap() *ListEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ListEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ListEntry) String() string {
	var builder strings.Builder
	builder.WriteString("ListEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("anilist_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnilistID))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Multiplier))
	builder.WriteString(", ")
	if v := _m.Order; v != nil {
		builder.WriteString("order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartAt; v != nil {
		builder.WriteString("start_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Split; v != nil {
		builder.WriteString("split=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("split_sequel_entry=")
	builder.WriteString(fmt.Sprintf("%v", _m.SplitSequelEntry))
	builder.WriteByte(')')
	return builder.String()
}

// ListEntries is a parsable slice of ListEntry.
type ListEntries []*ListEntry
