// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/user"
	"github.com/google/uuid"
)

// ListCreate is the builder for creating a List entity.
type ListCreate struct {
	config
	mutation *ListMutation
	hooks    []Hook
}

// SetSynchronizedAt sets the "synchronized_at" field.
func (_c *ListCreate) SetSynchronizedAt(v time.Time) *ListCreate {
	_c.mutation.SetSynchronizedAt(v)
	return _c
}

// SetNillableSynchronizedAt sets the "synchronized_at" field if the given value is not nil.
func (_c *ListCreate) SetNillableSynchronizedAt(v *time.Time) *ListCreate {
	if v != nil {
		_c.SetSynchronizedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ListCreate) SetCreatedAt(v time.Time) *ListCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ListCreate) SetNillableCreatedAt(v *time.Time) *ListCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ListCreate) SetUpdatedAt(v time.Time) *ListCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ListCreate) SetNillableUpdatedAt(v *time.Time) *ListCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ListCreate) SetName(v string) *ListCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ListCreate) SetDescription(v string) *ListCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetStackSize sets the "stack_size" field.
func (_c *ListCreate) SetStackSize(v uint) *ListCreate {
	_c.mutation.SetStackSize(v)
	return _c
}

// SetNillableStackSize sets the "stack_size" field if the given value is not nil.
func (_c *ListCreate) SetNillableStackSize(v *uint) *ListCreate {
	if v != nil {
		_c.SetStackSize(*v)
	}
	return _c
}

// SetAllowChunkMerge sets the "allow_chunk_merge" field.
func (_c *ListCreate) SetAllowChunkMerge(v bool) *ListCreate {
	_c.mutation.SetAllowChunkMerge(v)
	return _c
}

// SetNillableAllowChunkMerge sets the "allow_chunk_merge" field if the given value is not nil.
func (_c *ListCreate) SetNillableAllowChunkMerge(v *bool) *ListCreate {
	if v != nil {
		_c.SetAllowChunkMerge(*v)
	}
	return _c
}

// SetMaxChunkLength sets the "max_chunk_length" field.
func (_c *ListCreate) SetMaxChunkLength(v uint) *ListCreate {
	_c.mutation.SetMaxChunkLength(v)
	return _c
}

// SetNillableMaxChunkLength sets the "max_chunk_length" field if the given value is not nil.
func (_c *ListCreate) SetNillableMaxChunkLength(v *uint) *ListCreate {
	if v != nil {
		_c.SetMaxChunkLength(*v)
	}
	return _c
}

// SetMaxChunkJoinLength sets the "max_chunk_join_length" field.
func (_c *ListCreate) SetMaxChunkJoinLength(v uint) *ListCreate {
	_c.mutation.SetMaxChunkJoinLength(v)
	return _c
}

// SetNillableMaxChunkJoinLength sets the "max_chunk_join_length" field if the given value is not nil.
func (_c *ListCreate) SetNillableMaxChunkJoinLength(v *uint) *ListCreate {
	if v != nil {
		_c.SetMaxChunkJoinLength(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ListCreate) SetID(v uuid.UUID) *ListCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ListCreate) SetNillableID(v *uuid.UUID) *ListCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *ListCreate) SetOwnerID(id uuid.UUID) *ListCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *ListCreate) SetNillableOwnerID(id *uuid.UUID) *ListCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *ListCreate) SetOwner(v *User) *ListCreate {
	return _c.SetOwnerID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the ListEntry entity by IDs.
func (_c *ListCreate) AddEntryIDs(ids ...uuid.UUID) *ListCreate {
	_c.mutation.AddEntryIDs(ids...)
	return _c
}

// AddEntries adds the "entries" edges to the ListEntry entity.
func (_c *ListCreate) AddEntries(v ...*ListEntry) *ListCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntryIDs(ids...)
}

// Mutation returns the ListMutation object of the builder.
func (_c *ListCreate) Mutation() *ListMutation {
	return _c.mutation
}

// Save creates the List in the database.
func (_c *ListCreate) Save(ctx context.Context) (*List, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListCreate) SaveX(ctx context.Context) *List {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := list.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := list.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.StackSize(); !ok {
		v := list.DefaultStackSize
		_c.mutation.SetStackSize(v)
	}
	if _, ok := _c.mutation.AllowChunkMerge(); !ok {
		v := list.DefaultAllowChunkMerge
		_c.mutation.SetAllowChunkMerge(v)
	}
	if _, ok := _c.mutation.MaxChunkLength(); !ok {
		v := list.DefaultMaxChunkLength
		_c.mutation.SetMaxChunkLength(v)
	}
	if _, ok := _c.mutation.MaxChunkJoinLength(); !ok {
		v := list.DefaultMaxChunkJoinLength
		_c.mutation.SetMaxChunkJoinLength(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := list.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "List.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "List.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "List.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "List.description"`)}
	}
	if _, ok := _c.mutation.StackSize(); !ok {
		return &ValidationError{Name: "stack_size", err: errors.New(`ent: missing required field "List.stack_size"`)}
	}
	if _, ok := _c.mutation.AllowChunkMerge(); !ok {
		return &ValidationError{Name: "allow_chunk_merge", err: errors.New(`ent: missing required field "List.allow_chunk_merge"`)}
	}
	if _, ok := _c.mutation.MaxChunkLength(); !ok {
		return &ValidationError{Name: "max_chunk_length", err: errors.New(`ent: missing required field "List.max_chunk_length"`)}
	}
	if _, ok := _c.mutation.MaxChunkJoinLength(); !ok {
		return &ValidationError{Name: "max_chunk_join_length", err: errors.New(`ent: missing required field "List.max_chunk_join_length"`)}
	}
	return nil
}

func (_c *ListCreate) sqlSave(ctx context.Context) (*List, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListCreate) createSpec() (*List, *sqlgraph.CreateSpec) {
	var (
		_node = &List{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(list.Table, sqlgraph.NewFieldSpec(list.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SynchronizedAt(); ok {
		_spec.SetField(list.FieldSynchronizedAt, field.TypeTime, value)
		_node.SynchronizedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(list.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(list.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(list.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(list.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.StackSize(); ok {
		_spec.SetField(list.FieldStackSize, field.TypeUint, value)
		_node.StackSize = value
	}
	if value, ok := _c.mutation.AllowChunkMerge(); ok {
		_spec.SetField(list.FieldAllowChunkMerge, field.TypeBool, value)
		_node.AllowChunkMerge = value
	}
	if value, ok := _c.mutation.MaxChunkLength(); ok {
		_spec.SetField(list.FieldMaxChunkLength, field.TypeUint, value)
		_node.MaxChunkLength = value
	}
	if value, ok := _c.mutation.MaxChunkJoinLength(); ok {
		_spec.SetField(list.FieldMaxChunkJoinLength, field.TypeUint, value)
		_node.MaxChunkJoinLength = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   list.OwnerTable,
			Columns: []string{list.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_lists = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.EntriesTable,
			Columns: []string{list.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ListCreateBulk is the builder for creating many List entities in bulk.
type ListCreateBulk struct {
	config
	err      error
	builders []*ListCreate
}

// Save creates the List entities in the database.
func (_c *ListCreateBulk) Save(ctx context.Context) ([]*List, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*List, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListCreateBulk) SaveX(ctx context.Context) []*List {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
