// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/predicate"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"github.com/google/uuid"
)

// ListEntryQuery is the builder for querying ListEntry entities.
type ListEntryQuery struct {
	config
	ctx                    *QueryContext
	order                  []listentry.OrderOption
	inters                 []Interceptor
	predicates             []predicate.ListEntry
	withList               *ListQuery
	withSeries             *SeriesQuery
	withCustomSequelSeries *SeriesQuery
	withFKs                bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ListEntryQuery builder.
func (_q *ListEntryQuery) Where(ps ...predicate.ListEntry) *ListEntryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ListEntryQuery) Limit(limit int) *ListEntryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ListEntryQuery) Offset(offset int) *ListEntryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ListEntryQuery) Unique(unique bool) *ListEntryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ListEntryQuery) Order(o ...listentry.OrderOption) *ListEntryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryList chains the current query on the "list" edge.
func (_q *ListEntryQuery) QueryList() *ListQuery {
	query := (&ListClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(listentry.Table, listentry.FieldID, selector),
			sqlgraph.To(list.Table, list.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, listentry.ListTable, listentry.ListColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySeries chains the current query on the "series" edge.
func (_q *ListEntryQuery) QuerySeries() *SeriesQuery {
	query := (&SeriesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(listentry.Table, listentry.FieldID, selector),
			sqlgraph.To(series.Table, series.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, listentry.SeriesTable, listentry.SeriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCustomSequelSeries chains the current query on the "custom_sequel_series" edge.
func (_q *ListEntryQuery) QueryCustomSequelSeries() *SeriesQuery {
	query := (&SeriesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(listentry.Table, listentry.FieldID, selector),
			sqlgraph.To(series.Table, series.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, listentry.CustomSequelSeriesTable, listentry.CustomSequelSeriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ListEntry entity from the query.
// Returns a *NotFoundError when no ListEntry was found.
func (_q *ListEntryQuery) First(ctx context.Context) (*ListEntry, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{listentry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ListEntryQuery) FirstX(ctx context.Context) *ListEntry {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ListEntry ID from the query.
// Returns a *NotFoundError when no ListEntry ID was found.
func (_q *ListEntryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{listentry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ListEntryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ListEntry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ListEntry entity is found.
// Returns a *NotFoundError when no ListEntry entities are found.
func (_q *ListEntryQuery) Only(ctx context.Context) (*ListEntry, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{listentry.Label}
	default:
		return nil, &NotSingularError{listentry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ListEntryQuery) OnlyX(ctx context.Context) *ListEntry {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ListEntry ID in the query.
// Returns a *NotSingularError when more than one ListEntry ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ListEntryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{listentry.Label}
	default:
		err = &NotSingularError{listentry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ListEntryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ListEntries.
func (_q *ListEntryQuery) All(ctx context.Context) ([]*ListEntry, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ListEntry, *ListEntryQuery]()
	return withInterceptors[[]*ListEntry](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ListEntryQuery) AllX(ctx context.Context) []*ListEntry {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ListEntry IDs.
func (_q *ListEntryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(listentry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ListEntryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ListEntryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ListEntryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ListEntryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ListEntryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ListEntryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ListEntryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ListEntryQuery) Clone() *ListEntryQuery {
	if _q == nil {
		return nil
	}
	return &ListEntryQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]listentry.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.ListEntry{}, _q.predicates...),
		withList:               _q.withList.Clone(),
		withSeries:             _q.withSeries.Clone(),
		withCustomSequelSeries: _q.withCustomSequelSeries.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithList tells the query-builder to eager-load the nodes that are connected to
// the "list" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ListEntryQuery) WithList(opts ...func(*ListQuery)) *ListEntryQuery {
	query := (&ListClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withList = query
	return _q
}

// WithSeries tells the query-builder to eager-load the nodes that are connected to
// the "series" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ListEntryQuery) WithSeries(opts ...func(*SeriesQuery)) *ListEntryQuery {
	query := (&SeriesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSeries = query
	return _q
}

// WithCustomSequelSeries tells the query-builder to eager-load the nodes that are connected to
// the "custom_sequel_series" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ListEntryQuery) WithCustomSequelSeries(opts ...func(*SeriesQuery)) *ListEntryQuery {
	query := (&SeriesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCustomSequelSeries = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ListEntry.Query().
//		GroupBy(listentry.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ListEntryQuery) GroupBy(field string, fields ...string) *ListEntryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ListEntryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = listentry.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ListEntry.Query().
//		Select(listentry.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ListEntryQuery) Select(fields ...string) *ListEntrySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ListEntrySelect{ListEntryQuery: _q}
	sbuild.label = listentry.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ListEntrySelect configured with the given aggregations.
func (_q *ListEntryQuery) Aggregate(fns ...AggregateFunc) *ListEntrySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ListEntryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !listentry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ListEntryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ListEntry, error) {
	var (
		nodes       = []*ListEntry{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withList != nil,
			_q.withSeries != nil,
			_q.withCustomSequelSeries != nil,
		}
	)
	if _q.withList != nil || _q.withSeries != nil || _q.withCustomSequelSeries != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, listentry.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ListEntry).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ListEntry{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withList; query != nil {
		if err := _q.loadList(ctx, query, nodes, nil,
			func(n *ListEntry, e *List) { n.Edges.List = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSeries; query != nil {
		if err := _q.loadSeries(ctx, query, nodes, nil,
			func(n *ListEntry, e *Series) { n.Edges.Series = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCustomSequelSeries; query != nil {
		if err := _q.loadCustomSequelSeries(ctx, query, nodes, nil,
			func(n *ListEntry, e *Series) { n.Edges.CustomSequelSeries = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ListEntryQuery) loadList(ctx context.Context, query *ListQuery, nodes []*ListEntry, init func(*ListEntry), assign func(*ListEntry, *List)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ListEntry)
	for i := range nodes {
		if nodes[i].list_entries == nil {
			continue
		}
		fk := *nodes[i].list_entries
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(list.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "list_entries" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ListEntryQuery) loadSeries(ctx context.Context, query *SeriesQuery, nodes []*ListEntry, init func(*ListEntry), assign func(*ListEntry, *Series)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ListEntry)
	for i := range nodes {
		if nodes[i].list_entry_series == nil {
			continue
		}
		fk := *nodes[i].list_entry_series
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(series.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "list_entry_series" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ListEntryQuery) loadCustomSequelSeries(ctx context.Context, query *SeriesQuery, nodes []*ListEntry, init func(*ListEntry), assign func(*ListEntry, *Series)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ListEntry)
	for i := range nodes {
		if nodes[i].list_entry_custom_sequel_series == nil {
			continue
		}
		fk := *nodes[i].list_entry_custom_sequel_series
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(series.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "list_entry_custom_sequel_series" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ListEntryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ListEntryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(listentry.Table, listentry.Columns, sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listentry.FieldID)
		for i := range fields {
			if fields[i] != listentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ListEntryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(listentry.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = listentry.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ListEntryGroupBy is the group-by builder for ListEntry entities.
type ListEntryGroupBy struct {
	selector
	build *ListEntryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ListEntryGroupBy) Aggregate(fns ...AggregateFunc) *ListEntryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ListEntryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ListEntryQuery, *ListEntryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ListEntryGroupBy) sqlScan(ctx context.Context, root *ListEntryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ListEntrySelect is the builder for selecting fields of ListEntry entities.
type ListEntrySelect struct {
	*ListEntryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ListEntrySelect) Aggregate(fns ...AggregateFunc) *ListEntrySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ListEntrySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ListEntryQuery, *ListEntrySelect](ctx, _s.ListEntryQuery, _s, _s.inters, v)
}

func (_s *ListEntrySelect) sqlScan(ctx context.Context, root *ListEntryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
