// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/user"
	"github.com/google/uuid"
)

// List is the model entity for the List schema.
type List struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SynchronizedAt holds the value of the "synchronized_at" field.
	SynchronizedAt time.Time `json:"synchronized_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// StackSize holds the value of the "stack_size" field.
	StackSize uint `json:"stack_size,omitempty"`
	// AllowChunkMerge holds the value of the "allow_chunk_merge" field.
	AllowChunkMerge bool `json:"allow_chunk_merge,omitempty"`
	// MaxChunkLength holds the value of the "max_chunk_length" field.
	MaxChunkLength uint `json:"max_chunk_length,omitempty"`
	// MaxChunkJoinLength holds the value of the "max_chunk_join_length" field.
	MaxChunkJoinLength uint `json:"max_chunk_join_length,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ListQuery when eager-loading is set.
	Edges        ListEdges `json:"edges"`
	user_lists   *uuid.UUID
	selectValues sql.SelectValues
}

// ListEdges holds the relations/edges for other nodes in the graph.
type ListEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Entries holds the value of the entries edge.
	Entries []*ListEntry `json:"entries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// EntriesOrErr returns the Entries value or an error if the edge
// was not loaded in eager-loading.
func (e ListEdges) EntriesOrErr() ([]*ListEntry, error) {
	if e.loadedTypes[1] {
		return e.Entries, nil
	}
	return nil, &NotLoadedError{edge: "entries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*List) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case list.FieldAllowChunkMerge:
			values[i] = new(sql.NullBool)
		case list.FieldStackSize, list.FieldMaxChunkLength, list.FieldMaxChunkJoinLength:
			values[i] = new(sql.NullInt64)
		case list.FieldName, list.FieldDescription:
			values[i] = new(sql.NullString)
		case list.FieldSynchronizedAt, list.FieldCreatedAt, list.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case list.FieldID:
			values[i] = new(uuid.UUID)
		case list.ForeignKeys[0]: // user_lists
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the List fields.
func (_m *List) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case list.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case list.FieldSynchronizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synchronized_at", values[i])
			} else if value.Valid {
				_m.SynchronizedAt = value.Time
			}
		case list.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case list.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case list.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case list.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case list.FieldStackSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stack_size", values[i])
			} else if value.Valid {
				_m.StackSize = uint(value.Int64)
			}
		case list.FieldAllowChunkMerge:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_chunk_merge", values[i])
			} else if value.Valid {
				_m.AllowChunkMerge = value.Bool
			}
		case list.FieldMaxChunkLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_chunk_length", values[i])
			} else if value.Valid {
				_m.MaxChunkLength = uint(value.Int64)
			}
		case list.FieldMaxChunkJoinLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_chunk_join_length", values[i])
			} else if value.Valid {
				_m.MaxChunkJoinLength = uint(value.Int64)
			}
		case list.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_lists", values[i])
			} else if value.Valid {
				_m.user_lists = new(uuid.UUID)
				*_m.user_lists = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the List.
// This includes values selected through modifiers, order, etc.
func (_m *List) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the List entity.
func (_m *List) QueryOwner() *UserQuery {
	return NewListClient(_m.config).QueryOwner(_m)
}

// QueryEntries queries the "entries" edge of the List entity.
func (_m *List) QueryEntries() *ListEntryQuery {
	return NewListClient(_m.config).QueryEntries(_m)
}

// Update returns a builder for updating this List.
// Note that you need to call List.Unwrap() before calling this method if this List
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *List) Update() *ListUpdateOne {
	return NewListClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the List entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *List) Unwrap() *List {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: List is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *List) String() string {
	var builder strings.Builder
	builder.WriteString("List(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("synchronized_at=")
	builder.WriteString(_m.SynchronizedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("stack_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.StackSize))
	builder.WriteString(", ")
	builder.WriteString("allow_chunk_merge=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowChunkMerge))
	builder.WriteString(", ")
	builder.WriteString("max_chunk_length=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxChunkLength))
	builder.WriteString(", ")
	builder.WriteString("max_chunk_join_length=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxChunkJoinLength))
	builder.WriteByte(')')
	return builder.String()
}

// Lists is a parsable slice of List.
type Lists []*List
