// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"git.jojoxd.nl/projects/anistats/backend/ent/list"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/schema"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"git.jojoxd.nl/projects/anistats/backend/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	listMixin := schema.List{}.Mixin()
	listMixinFields1 := listMixin[1].Fields()
	_ = listMixinFields1
	listFields := schema.List{}.Fields()
	_ = listFields
	// listDescCreatedAt is the schema descriptor for created_at field.
	listDescCreatedAt := listMixinFields1[0].Descriptor()
	// list.DefaultCreatedAt holds the default value on creation for the created_at field.
	list.DefaultCreatedAt = listDescCreatedAt.Default.(func() time.Time)
	// listDescUpdatedAt is the schema descriptor for updated_at field.
	listDescUpdatedAt := listMixinFields1[1].Descriptor()
	// list.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	list.DefaultUpdatedAt = listDescUpdatedAt.Default.(func() time.Time)
	// list.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	list.UpdateDefaultUpdatedAt = listDescUpdatedAt.UpdateDefault.(func() time.Time)
	// listDescStackSize is the schema descriptor for stack_size field.
	listDescStackSize := listFields[3].Descriptor()
	// list.DefaultStackSize holds the default value on creation for the stack_size field.
	list.DefaultStackSize = listDescStackSize.Default.(uint)
	// listDescAllowChunkMerge is the schema descriptor for allow_chunk_merge field.
	listDescAllowChunkMerge := listFields[4].Descriptor()
	// list.DefaultAllowChunkMerge holds the default value on creation for the allow_chunk_merge field.
	list.DefaultAllowChunkMerge = listDescAllowChunkMerge.Default.(bool)
	// listDescMaxChunkLength is the schema descriptor for max_chunk_length field.
	listDescMaxChunkLength := listFields[5].Descriptor()
	// list.DefaultMaxChunkLength holds the default value on creation for the max_chunk_length field.
	list.DefaultMaxChunkLength = listDescMaxChunkLength.Default.(uint)
	// listDescMaxChunkJoinLength is the schema descriptor for max_chunk_join_length field.
	listDescMaxChunkJoinLength := listFields[6].Descriptor()
	// list.DefaultMaxChunkJoinLength holds the default value on creation for the max_chunk_join_length field.
	list.DefaultMaxChunkJoinLength = listDescMaxChunkJoinLength.Default.(uint)
	// listDescID is the schema descriptor for id field.
	listDescID := listFields[0].Descriptor()
	// list.DefaultID holds the default value on creation for the id field.
	list.DefaultID = listDescID.Default.(func() uuid.UUID)
	listentryMixin := schema.ListEntry{}.Mixin()
	listentryMixinFields0 := listentryMixin[0].Fields()
	_ = listentryMixinFields0
	listentryFields := schema.ListEntry{}.Fields()
	_ = listentryFields
	// listentryDescCreatedAt is the schema descriptor for created_at field.
	listentryDescCreatedAt := listentryMixinFields0[0].Descriptor()
	// listentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	listentry.DefaultCreatedAt = listentryDescCreatedAt.Default.(func() time.Time)
	// listentryDescUpdatedAt is the schema descriptor for updated_at field.
	listentryDescUpdatedAt := listentryMixinFields0[1].Descriptor()
	// listentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listentry.DefaultUpdatedAt = listentryDescUpdatedAt.Default.(func() time.Time)
	// listentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listentry.UpdateDefaultUpdatedAt = listentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// listentryDescProgress is the schema descriptor for progress field.
	listentryDescProgress := listentryFields[3].Descriptor()
	// listentry.DefaultProgress holds the default value on creation for the progress field.
	listentry.DefaultProgress = listentryDescProgress.Default.(uint)
	// listentryDescMultiplier is the schema descriptor for multiplier field.
	listentryDescMultiplier := listentryFields[4].Descriptor()
	// listentry.DefaultMultiplier holds the default value on creation for the multiplier field.
	listentry.DefaultMultiplier = listentryDescMultiplier.Default.(float64)
	// listentryDescSplitSequelEntry is the schema descriptor for split_sequel_entry field.
	listentryDescSplitSequelEntry := listentryFields[8].Descriptor()
	// listentry.DefaultSplitSequelEntry holds the default value on creation for the split_sequel_entry field.
	listentry.DefaultSplitSequelEntry = listentryDescSplitSequelEntry.Default.(bool)
	// listentryDescID is the schema descriptor for id field.
	listentryDescID := listentryFields[0].Descriptor()
	// listentry.DefaultID holds the default value on creation for the id field.
	listentry.DefaultID = listentryDescID.Default.(func() uuid.UUID)
	seriesMixin := schema.Series{}.Mixin()
	seriesMixinFields1 := seriesMixin[1].Fields()
	_ = seriesMixinFields1
	seriesFields := schema.Series{}.Fields()
	_ = seriesFields
	// seriesDescCreatedAt is the schema descriptor for created_at field.
	seriesDescCreatedAt := seriesMixinFields1[0].Descriptor()
	// series.DefaultCreatedAt holds the default value on creation for the created_at field.
	series.DefaultCreatedAt = seriesDescCreatedAt.Default.(func() time.Time)
	// seriesDescUpdatedAt is the schema descriptor for updated_at field.
	seriesDescUpdatedAt := seriesMixinFields1[1].Descriptor()
	// series.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	series.DefaultUpdatedAt = seriesDescUpdatedAt.Default.(func() time.Time)
	// series.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	series.UpdateDefaultUpdatedAt = seriesDescUpdatedAt.UpdateDefault.(func() time.Time)
	// seriesDescID is the schema descriptor for id field.
	seriesDescID := seriesFields[0].Descriptor()
	// series.DefaultID holds the default value on creation for the id field.
	series.DefaultID = seriesDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
