// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/predicate"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"github.com/google/uuid"
)

// SeriesUpdate is the builder for updating Series entities.
type SeriesUpdate struct {
	config
	hooks    []Hook
	mutation *SeriesMutation
}

// Where appends a list predicates to the SeriesUpdate builder.
func (_u *SeriesUpdate) Where(ps ...predicate.Series) *SeriesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSynchronizedAt sets the "synchronized_at" field.
func (_u *SeriesUpdate) SetSynchronizedAt(v time.Time) *SeriesUpdate {
	_u.mutation.SetSynchronizedAt(v)
	return _u
}

// SetNillableSynchronizedAt sets the "synchronized_at" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableSynchronizedAt(v *time.Time) *SeriesUpdate {
	if v != nil {
		_u.SetSynchronizedAt(*v)
	}
	return _u
}

// ClearSynchronizedAt clears the value of the "synchronized_at" field.
func (_u *SeriesUpdate) ClearSynchronizedAt() *SeriesUpdate {
	_u.mutation.ClearSynchronizedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SeriesUpdate) SetUpdatedAt(v time.Time) *SeriesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAnilistID sets the "anilist_id" field.
func (_u *SeriesUpdate) SetAnilistID(v uint) *SeriesUpdate {
	_u.mutation.ResetAnilistID()
	_u.mutation.SetAnilistID(v)
	return _u
}

// SetNillableAnilistID sets the "anilist_id" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableAnilistID(v *uint) *SeriesUpdate {
	if v != nil {
		_u.SetAnilistID(*v)
	}
	return _u
}

// AddAnilistID adds value to the "anilist_id" field.
func (_u *SeriesUpdate) AddAnilistID(v int) *SeriesUpdate {
	_u.mutation.AddAnilistID(v)
	return _u
}

// SetTitleEnglish sets the "title_english" field.
func (_u *SeriesUpdate) SetTitleEnglish(v string) *SeriesUpdate {
	_u.mutation.SetTitleEnglish(v)
	return _u
}

// SetNillableTitleEnglish sets the "title_english" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableTitleEnglish(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetTitleEnglish(*v)
	}
	return _u
}

// SetTitleNative sets the "title_native" field.
func (_u *SeriesUpdate) SetTitleNative(v string) *SeriesUpdate {
	_u.mutation.SetTitleNative(v)
	return _u
}

// SetNillableTitleNative sets the "title_native" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableTitleNative(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetTitleNative(*v)
	}
	return _u
}

// SetTitleRomaji sets the "title_romaji" field.
func (_u *SeriesUpdate) SetTitleRomaji(v string) *SeriesUpdate {
	_u.mutation.SetTitleRomaji(v)
	return _u
}

// SetNillableTitleRomaji sets the "title_romaji" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableTitleRomaji(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetTitleRomaji(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SeriesUpdate) SetDescription(v string) *SeriesUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableDescription(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *SeriesUpdate) SetCoverImageURL(v string) *SeriesUpdate {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableCoverImageURL(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// SetEpisodes sets the "episodes" field.
func (_u *SeriesUpdate) SetEpisodes(v uint) *SeriesUpdate {
	_u.mutation.ResetEpisodes()
	_u.mutation.SetEpisodes(v)
	return _u
}

// SetNillableEpisodes sets the "episodes" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableEpisodes(v *uint) *SeriesUpdate {
	if v != nil {
		_u.SetEpisodes(*v)
	}
	return _u
}

// AddEpisodes adds value to the "episodes" field.
func (_u *SeriesUpdate) AddEpisodes(v int) *SeriesUpdate {
	_u.mutation.AddEpisodes(v)
	return _u
}

// SetDuration sets the "duration" field.
func (_u *SeriesUpdate) SetDuration(v time.Duration) *SeriesUpdate {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableDuration(v *time.Duration) *SeriesUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *SeriesUpdate) AddDuration(v time.Duration) *SeriesUpdate {
	_u.mutation.AddDuration(v)
	return _u
}

// AddReferencedInIDs adds the "referenced_in" edge to the ListEntry entity by IDs.
func (_u *SeriesUpdate) AddReferencedInIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.AddReferencedInIDs(ids...)
	return _u
}

// AddReferencedIn adds the "referenced_in" edges to the ListEntry entity.
func (_u *SeriesUpdate) AddReferencedIn(v ...*ListEntry) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferencedInIDs(ids...)
}

// AddCustomSequelOfIDs adds the "custom_sequel_of" edge to the ListEntry entity by IDs.
func (_u *SeriesUpdate) AddCustomSequelOfIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.AddCustomSequelOfIDs(ids...)
	return _u
}

// AddCustomSequelOf adds the "custom_sequel_of" edges to the ListEntry entity.
func (_u *SeriesUpdate) AddCustomSequelOf(v ...*ListEntry) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomSequelOfIDs(ids...)
}

// AddPrequelIDs adds the "prequels" edge to the Series entity by IDs.
func (_u *SeriesUpdate) AddPrequelIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.AddPrequelIDs(ids...)
	return _u
}

// AddPrequels adds the "prequels" edges to the Series entity.
func (_u *SeriesUpdate) AddPrequels(v ...*Series) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrequelIDs(ids...)
}

// AddSequelIDs adds the "sequels" edge to the Series entity by IDs.
func (_u *SeriesUpdate) AddSequelIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.AddSequelIDs(ids...)
	return _u
}

// AddSequels adds the "sequels" edges to the Series entity.
func (_u *SeriesUpdate) AddSequels(v ...*Series) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSequelIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_u *SeriesUpdate) Mutation() *SeriesMutation {
	return _u.mutation
}

// ClearReferencedIn clears all "referenced_in" edges to the ListEntry entity.
func (_u *SeriesUpdate) ClearReferencedIn() *SeriesUpdate {
	_u.mutation.ClearReferencedIn()
	return _u
}

// RemoveReferencedInIDs removes the "referenced_in" edge to ListEntry entities by IDs.
func (_u *SeriesUpdate) RemoveReferencedInIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.RemoveReferencedInIDs(ids...)
	return _u
}

// RemoveReferencedIn removes "referenced_in" edges to ListEntry entities.
func (_u *SeriesUpdate) RemoveReferencedIn(v ...*ListEntry) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferencedInIDs(ids...)
}

// ClearCustomSequelOf clears all "custom_sequel_of" edges to the ListEntry entity.
func (_u *SeriesUpdate) ClearCustomSequelOf() *SeriesUpdate {
	_u.mutation.ClearCustomSequelOf()
	return _u
}

// RemoveCustomSequelOfIDs removes the "custom_sequel_of" edge to ListEntry entities by IDs.
func (_u *SeriesUpdate) RemoveCustomSequelOfIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.RemoveCustomSequelOfIDs(ids...)
	return _u
}

// RemoveCustomSequelOf removes "custom_sequel_of" edges to ListEntry entities.
func (_u *SeriesUpdate) RemoveCustomSequelOf(v ...*ListEntry) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomSequelOfIDs(ids...)
}

// ClearPrequels clears all "prequels" edges to the Series entity.
func (_u *SeriesUpdate) ClearPrequels() *SeriesUpdate {
	_u.mutation.ClearPrequels()
	return _u
}

// RemovePrequelIDs removes the "prequels" edge to Series entities by IDs.
func (_u *SeriesUpdate) RemovePrequelIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.RemovePrequelIDs(ids...)
	return _u
}

// RemovePrequels removes "prequels" edges to Series entities.
func (_u *SeriesUpdate) RemovePrequels(v ...*Series) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrequelIDs(ids...)
}

// ClearSequels clears all "sequels" edges to the Series entity.
func (_u *SeriesUpdate) ClearSequels() *SeriesUpdate {
	_u.mutation.ClearSequels()
	return _u
}

// RemoveSequelIDs removes the "sequels" edge to Series entities by IDs.
func (_u *SeriesUpdate) RemoveSequelIDs(ids ...uuid.UUID) *SeriesUpdate {
	_u.mutation.RemoveSequelIDs(ids...)
	return _u
}

// RemoveSequels removes "sequels" edges to Series entities.
func (_u *SeriesUpdate) RemoveSequels(v ...*Series) *SeriesUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSequelIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SeriesUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SeriesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SeriesUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := series.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SeriesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SynchronizedAt(); ok {
		_spec.SetField(series.FieldSynchronizedAt, field.TypeTime, value)
	}
	if _u.mutation.SynchronizedAtCleared() {
		_spec.ClearField(series.FieldSynchronizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(series.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AnilistID(); ok {
		_spec.SetField(series.FieldAnilistID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedAnilistID(); ok {
		_spec.AddField(series.FieldAnilistID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TitleEnglish(); ok {
		_spec.SetField(series.FieldTitleEnglish, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleNative(); ok {
		_spec.SetField(series.FieldTitleNative, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleRomaji(); ok {
		_spec.SetField(series.FieldTitleRomaji, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(series.FieldCoverImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Episodes(); ok {
		_spec.SetField(series.FieldEpisodes, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedEpisodes(); ok {
		_spec.AddField(series.FieldEpisodes, field.TypeUint, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(series.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(series.FieldDuration, field.TypeInt64, value)
	}
	if _u.mutation.ReferencedInCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencedInIDs(); len(nodes) > 0 && !_u.mutation.ReferencedInCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedInIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomSequelOfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomSequelOfIDs(); len(nodes) > 0 && !_u.mutation.CustomSequelOfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomSequelOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrequelsIDs(); len(nodes) > 0 && !_u.mutation.PrequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrequelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSequelsIDs(); len(nodes) > 0 && !_u.mutation.SequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SequelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SeriesUpdateOne is the builder for updating a single Series entity.
type SeriesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SeriesMutation
}

// SetSynchronizedAt sets the "synchronized_at" field.
func (_u *SeriesUpdateOne) SetSynchronizedAt(v time.Time) *SeriesUpdateOne {
	_u.mutation.SetSynchronizedAt(v)
	return _u
}

// SetNillableSynchronizedAt sets the "synchronized_at" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableSynchronizedAt(v *time.Time) *SeriesUpdateOne {
	if v != nil {
		_u.SetSynchronizedAt(*v)
	}
	return _u
}

// ClearSynchronizedAt clears the value of the "synchronized_at" field.
func (_u *SeriesUpdateOne) ClearSynchronizedAt() *SeriesUpdateOne {
	_u.mutation.ClearSynchronizedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SeriesUpdateOne) SetUpdatedAt(v time.Time) *SeriesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAnilistID sets the "anilist_id" field.
func (_u *SeriesUpdateOne) SetAnilistID(v uint) *SeriesUpdateOne {
	_u.mutation.ResetAnilistID()
	_u.mutation.SetAnilistID(v)
	return _u
}

// SetNillableAnilistID sets the "anilist_id" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableAnilistID(v *uint) *SeriesUpdateOne {
	if v != nil {
		_u.SetAnilistID(*v)
	}
	return _u
}

// AddAnilistID adds value to the "anilist_id" field.
func (_u *SeriesUpdateOne) AddAnilistID(v int) *SeriesUpdateOne {
	_u.mutation.AddAnilistID(v)
	return _u
}

// SetTitleEnglish sets the "title_english" field.
func (_u *SeriesUpdateOne) SetTitleEnglish(v string) *SeriesUpdateOne {
	_u.mutation.SetTitleEnglish(v)
	return _u
}

// SetNillableTitleEnglish sets the "title_english" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableTitleEnglish(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetTitleEnglish(*v)
	}
	return _u
}

// SetTitleNative sets the "title_native" field.
func (_u *SeriesUpdateOne) SetTitleNative(v string) *SeriesUpdateOne {
	_u.mutation.SetTitleNative(v)
	return _u
}

// SetNillableTitleNative sets the "title_native" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableTitleNative(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetTitleNative(*v)
	}
	return _u
}

// SetTitleRomaji sets the "title_romaji" field.
func (_u *SeriesUpdateOne) SetTitleRomaji(v string) *SeriesUpdateOne {
	_u.mutation.SetTitleRomaji(v)
	return _u
}

// SetNillableTitleRomaji sets the "title_romaji" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableTitleRomaji(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetTitleRomaji(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SeriesUpdateOne) SetDescription(v string) *SeriesUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableDescription(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *SeriesUpdateOne) SetCoverImageURL(v string) *SeriesUpdateOne {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableCoverImageURL(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// SetEpisodes sets the "episodes" field.
func (_u *SeriesUpdateOne) SetEpisodes(v uint) *SeriesUpdateOne {
	_u.mutation.ResetEpisodes()
	_u.mutation.SetEpisodes(v)
	return _u
}

// SetNillableEpisodes sets the "episodes" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableEpisodes(v *uint) *SeriesUpdateOne {
	if v != nil {
		_u.SetEpisodes(*v)
	}
	return _u
}

// AddEpisodes adds value to the "episodes" field.
func (_u *SeriesUpdateOne) AddEpisodes(v int) *SeriesUpdateOne {
	_u.mutation.AddEpisodes(v)
	return _u
}

// SetDuration sets the "duration" field.
func (_u *SeriesUpdateOne) SetDuration(v time.Duration) *SeriesUpdateOne {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableDuration(v *time.Duration) *SeriesUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *SeriesUpdateOne) AddDuration(v time.Duration) *SeriesUpdateOne {
	_u.mutation.AddDuration(v)
	return _u
}

// AddReferencedInIDs adds the "referenced_in" edge to the ListEntry entity by IDs.
func (_u *SeriesUpdateOne) AddReferencedInIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.AddReferencedInIDs(ids...)
	return _u
}

// AddReferencedIn adds the "referenced_in" edges to the ListEntry entity.
func (_u *SeriesUpdateOne) AddReferencedIn(v ...*ListEntry) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferencedInIDs(ids...)
}

// AddCustomSequelOfIDs adds the "custom_sequel_of" edge to the ListEntry entity by IDs.
func (_u *SeriesUpdateOne) AddCustomSequelOfIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.AddCustomSequelOfIDs(ids...)
	return _u
}

// AddCustomSequelOf adds the "custom_sequel_of" edges to the ListEntry entity.
func (_u *SeriesUpdateOne) AddCustomSequelOf(v ...*ListEntry) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomSequelOfIDs(ids...)
}

// AddPrequelIDs adds the "prequels" edge to the Series entity by IDs.
func (_u *SeriesUpdateOne) AddPrequelIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.AddPrequelIDs(ids...)
	return _u
}

// AddPrequels adds the "prequels" edges to the Series entity.
func (_u *SeriesUpdateOne) AddPrequels(v ...*Series) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrequelIDs(ids...)
}

// AddSequelIDs adds the "sequels" edge to the Series entity by IDs.
func (_u *SeriesUpdateOne) AddSequelIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.AddSequelIDs(ids...)
	return _u
}

// AddSequels adds the "sequels" edges to the Series entity.
func (_u *SeriesUpdateOne) AddSequels(v ...*Series) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSequelIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_u *SeriesUpdateOne) Mutation() *SeriesMutation {
	return _u.mutation
}

// ClearReferencedIn clears all "referenced_in" edges to the ListEntry entity.
func (_u *SeriesUpdateOne) ClearReferencedIn() *SeriesUpdateOne {
	_u.mutation.ClearReferencedIn()
	return _u
}

// RemoveReferencedInIDs removes the "referenced_in" edge to ListEntry entities by IDs.
func (_u *SeriesUpdateOne) RemoveReferencedInIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.RemoveReferencedInIDs(ids...)
	return _u
}

// RemoveReferencedIn removes "referenced_in" edges to ListEntry entities.
func (_u *SeriesUpdateOne) RemoveReferencedIn(v ...*ListEntry) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferencedInIDs(ids...)
}

// ClearCustomSequelOf clears all "custom_sequel_of" edges to the ListEntry entity.
func (_u *SeriesUpdateOne) ClearCustomSequelOf() *SeriesUpdateOne {
	_u.mutation.ClearCustomSequelOf()
	return _u
}

// RemoveCustomSequelOfIDs removes the "custom_sequel_of" edge to ListEntry entities by IDs.
func (_u *SeriesUpdateOne) RemoveCustomSequelOfIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.RemoveCustomSequelOfIDs(ids...)
	return _u
}

// RemoveCustomSequelOf removes "custom_sequel_of" edges to ListEntry entities.
func (_u *SeriesUpdateOne) RemoveCustomSequelOf(v ...*ListEntry) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomSequelOfIDs(ids...)
}

// ClearPrequels clears all "prequels" edges to the Series entity.
func (_u *SeriesUpdateOne) ClearPrequels() *SeriesUpdateOne {
	_u.mutation.ClearPrequels()
	return _u
}

// RemovePrequelIDs removes the "prequels" edge to Series entities by IDs.
func (_u *SeriesUpdateOne) RemovePrequelIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.RemovePrequelIDs(ids...)
	return _u
}

// RemovePrequels removes "prequels" edges to Series entities.
func (_u *SeriesUpdateOne) RemovePrequels(v ...*Series) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrequelIDs(ids...)
}

// ClearSequels clears all "sequels" edges to the Series entity.
func (_u *SeriesUpdateOne) ClearSequels() *SeriesUpdateOne {
	_u.mutation.ClearSequels()
	return _u
}

// RemoveSequelIDs removes the "sequels" edge to Series entities by IDs.
func (_u *SeriesUpdateOne) RemoveSequelIDs(ids ...uuid.UUID) *SeriesUpdateOne {
	_u.mutation.RemoveSequelIDs(ids...)
	return _u
}

// RemoveSequels removes "sequels" edges to Series entities.
func (_u *SeriesUpdateOne) RemoveSequels(v ...*Series) *SeriesUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSequelIDs(ids...)
}

// Where appends a list predicates to the SeriesUpdate builder.
func (_u *SeriesUpdateOne) Where(ps ...predicate.Series) *SeriesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SeriesUpdateOne) Select(field string, fields ...string) *SeriesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Series entity.
func (_u *SeriesUpdateOne) Save(ctx context.Context) (*Series, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesUpdateOne) SaveX(ctx context.Context) *Series {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SeriesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SeriesUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := series.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SeriesUpdateOne) sqlSave(ctx context.Context) (_node *Series, err error) {
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Series.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, series.FieldID)
		for _, f := range fields {
			if !series.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != series.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SynchronizedAt(); ok {
		_spec.SetField(series.FieldSynchronizedAt, field.TypeTime, value)
	}
	if _u.mutation.SynchronizedAtCleared() {
		_spec.ClearField(series.FieldSynchronizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(series.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AnilistID(); ok {
		_spec.SetField(series.FieldAnilistID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedAnilistID(); ok {
		_spec.AddField(series.FieldAnilistID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TitleEnglish(); ok {
		_spec.SetField(series.FieldTitleEnglish, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleNative(); ok {
		_spec.SetField(series.FieldTitleNative, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleRomaji(); ok {
		_spec.SetField(series.FieldTitleRomaji, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(series.FieldCoverImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Episodes(); ok {
		_spec.SetField(series.FieldEpisodes, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedEpisodes(); ok {
		_spec.AddField(series.FieldEpisodes, field.TypeUint, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(series.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(series.FieldDuration, field.TypeInt64, value)
	}
	if _u.mutation.ReferencedInCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencedInIDs(); len(nodes) > 0 && !_u.mutation.ReferencedInCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedInIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomSequelOfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomSequelOfIDs(); len(nodes) > 0 && !_u.mutation.CustomSequelOfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomSequelOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrequelsIDs(); len(nodes) > 0 && !_u.mutation.PrequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrequelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSequelsIDs(); len(nodes) > 0 && !_u.mutation.SequelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SequelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Series{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
