// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"github.com/google/uuid"
)

// Series is the model entity for the Series schema.
type Series struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SynchronizedAt holds the value of the "synchronized_at" field.
	SynchronizedAt time.Time `json:"synchronized_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AnilistID holds the value of the "anilist_id" field.
	AnilistID uint `json:"anilist_id,omitempty"`
	// TitleEnglish holds the value of the "title_english" field.
	TitleEnglish *string `json:"title_english,omitempty"`
	// TitleNative holds the value of the "title_native" field.
	TitleNative *string `json:"title_native,omitempty"`
	// TitleRomaji holds the value of the "title_romaji" field.
	TitleRomaji *string `json:"title_romaji,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CoverImageURL holds the value of the "cover_image_url" field.
	CoverImageURL string `json:"cover_image_url,omitempty"`
	// Episodes holds the value of the "episodes" field.
	Episodes uint `json:"episodes,omitempty"`
	// Duration holds the value of the "duration" field.
	Duration time.Duration `json:"duration,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SeriesQuery when eager-loading is set.
	Edges        SeriesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SeriesEdges holds the relations/edges for other nodes in the graph.
type SeriesEdges struct {
	// ReferencedIn holds the value of the referenced_in edge.
	ReferencedIn []*ListEntry `json:"referenced_in,omitempty"`
	// CustomSequelOf holds the value of the custom_sequel_of edge.
	CustomSequelOf []*ListEntry `json:"custom_sequel_of,omitempty"`
	// Prequels holds the value of the prequels edge.
	Prequels []*Series `json:"prequels,omitempty"`
	// Sequels holds the value of the sequels edge.
	Sequels []*Series `json:"sequels,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ReferencedInOrErr returns the ReferencedIn value or an error if the edge
// was not loaded in eager-loading.
func (e SeriesEdges) ReferencedInOrErr() ([]*ListEntry, error) {
	if e.loadedTypes[0] {
		return e.ReferencedIn, nil
	}
	return nil, &NotLoadedError{edge: "referenced_in"}
}

// CustomSequelOfOrErr returns the CustomSequelOf value or an error if the edge
// was not loaded in eager-loading.
func (e SeriesEdges) CustomSequelOfOrErr() ([]*ListEntry, error) {
	if e.loadedTypes[1] {
		return e.CustomSequelOf, nil
	}
	return nil, &NotLoadedError{edge: "custom_sequel_of"}
}

// PrequelsOrErr returns the Prequels value or an error if the edge
// was not loaded in eager-loading.
func (e SeriesEdges) PrequelsOrErr() ([]*Series, error) {
	if e.loadedTypes[2] {
		return e.Prequels, nil
	}
	return nil, &NotLoadedError{edge: "prequels"}
}

// SequelsOrErr returns the Sequels value or an error if the edge
// was not loaded in eager-loading.
func (e SeriesEdges) SequelsOrErr() ([]*Series, error) {
	if e.loadedTypes[3] {
		return e.Sequels, nil
	}
	return nil, &NotLoadedError{edge: "sequels"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Series) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case series.FieldAnilistID, series.FieldEpisodes, series.FieldDuration:
			values[i] = new(sql.NullInt64)
		case series.FieldTitleEnglish, series.FieldTitleNative, series.FieldTitleRomaji, series.FieldDescription, series.FieldCoverImageURL:
			values[i] = new(sql.NullString)
		case series.FieldSynchronizedAt, series.FieldCreatedAt, series.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case series.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Series fields.
func (_m *Series) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case series.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case series.FieldSynchronizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synchronized_at", values[i])
			} else if value.Valid {
				_m.SynchronizedAt = value.Time
			}
		case series.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case series.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case series.FieldAnilistID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field anilist_id", values[i])
			} else if value.Valid {
				_m.AnilistID = uint(value.Int64)
			}
		case series.FieldTitleEnglish:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_english", values[i])
			} else if value.Valid {
				_m.TitleEnglish = new(string)
				*_m.TitleEnglish = value.String
			}
		case series.FieldTitleNative:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_native", values[i])
			} else if value.Valid {
				_m.TitleNative = new(string)
				*_m.TitleNative = value.String
			}
		case series.FieldTitleRomaji:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_romaji", values[i])
			} else if value.Valid {
				_m.TitleRomaji = new(string)
				*_m.TitleRomaji = value.String
			}
		case series.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case series.FieldCoverImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_image_url", values[i])
			} else if value.Valid {
				_m.CoverImageURL = value.String
			}
		case series.FieldEpisodes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field episodes", values[i])
			} else if value.Valid {
				_m.Episodes = uint(value.Int64)
			}
		case series.FieldDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				_m.Duration = time.Duration(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Series.
// This includes values selected through modifiers, order, etc.
func (_m *Series) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReferencedIn queries the "referenced_in" edge of the Series entity.
func (_m *Series) QueryReferencedIn() *ListEntryQuery {
	return NewSeriesClient(_m.config).QueryReferencedIn(_m)
}

// QueryCustomSequelOf queries the "custom_sequel_of" edge of the Series entity.
func (_m *Series) QueryCustomSequelOf() *ListEntryQuery {
	return NewSeriesClient(_m.config).QueryCustomSequelOf(_m)
}

// QueryPrequels queries the "prequels" edge of the Series entity.
func (_m *Series) QueryPrequels() *SeriesQuery {
	return NewSeriesClient(_m.config).QueryPrequels(_m)
}

// QuerySequels queries the "sequels" edge of the Series entity.
func (_m *Series) QuerySequels() *SeriesQuery {
	return NewSeriesClient(_m.config).QuerySequels(_m)
}

// Update returns a builder for updating this Series.
// Note that you need to call Series.Unwrap() before calling this method if this Series
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Series) Update() *SeriesUpdateOne {
	return NewSeriesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Series entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Series) Unwrap() *Series {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Series is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Series) String() string {
	var builder strings.Builder
	builder.WriteString("Series(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("synchronized_at=")
	builder.WriteString(_m.SynchronizedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("anilist_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnilistID))
	builder.WriteString(", ")
	if v := _m.TitleEnglish; v != nil {
		builder.WriteString("title_english=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TitleNative; v != nil {
		builder.WriteString("title_native=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TitleRomaji; v != nil {
		builder.WriteString("title_romaji=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("cover_image_url=")
	builder.WriteString(_m.CoverImageURL)
	builder.WriteString(", ")
	builder.WriteString("episodes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Episodes))
	builder.WriteString(", ")
	builder.WriteString("duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.Duration))
	builder.WriteByte(')')
	return builder.String()
}

// SeriesSlice is a parsable slice of Series.
type SeriesSlice []*Series
