// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.jojoxd.nl/projects/anistats/backend/ent/listentry"
	"git.jojoxd.nl/projects/anistats/backend/ent/series"
	"github.com/google/uuid"
)

// SeriesCreate is the builder for creating a Series entity.
type SeriesCreate struct {
	config
	mutation *SeriesMutation
	hooks    []Hook
}

// SetSynchronizedAt sets the "synchronized_at" field.
func (_c *SeriesCreate) SetSynchronizedAt(v time.Time) *SeriesCreate {
	_c.mutation.SetSynchronizedAt(v)
	return _c
}

// SetNillableSynchronizedAt sets the "synchronized_at" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableSynchronizedAt(v *time.Time) *SeriesCreate {
	if v != nil {
		_c.SetSynchronizedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SeriesCreate) SetCreatedAt(v time.Time) *SeriesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCreatedAt(v *time.Time) *SeriesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SeriesCreate) SetUpdatedAt(v time.Time) *SeriesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableUpdatedAt(v *time.Time) *SeriesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAnilistID sets the "anilist_id" field.
func (_c *SeriesCreate) SetAnilistID(v uint) *SeriesCreate {
	_c.mutation.SetAnilistID(v)
	return _c
}

// SetTitleEnglish sets the "title_english" field.
func (_c *SeriesCreate) SetTitleEnglish(v string) *SeriesCreate {
	_c.mutation.SetTitleEnglish(v)
	return _c
}

// SetTitleNative sets the "title_native" field.
func (_c *SeriesCreate) SetTitleNative(v string) *SeriesCreate {
	_c.mutation.SetTitleNative(v)
	return _c
}

// SetTitleRomaji sets the "title_romaji" field.
func (_c *SeriesCreate) SetTitleRomaji(v string) *SeriesCreate {
	_c.mutation.SetTitleRomaji(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SeriesCreate) SetDescription(v string) *SeriesCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_c *SeriesCreate) SetCoverImageURL(v string) *SeriesCreate {
	_c.mutation.SetCoverImageURL(v)
	return _c
}

// SetEpisodes sets the "episodes" field.
func (_c *SeriesCreate) SetEpisodes(v uint) *SeriesCreate {
	_c.mutation.SetEpisodes(v)
	return _c
}

// SetDuration sets the "duration" field.
func (_c *SeriesCreate) SetDuration(v time.Duration) *SeriesCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SeriesCreate) SetID(v uuid.UUID) *SeriesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableID(v *uuid.UUID) *SeriesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddReferencedInIDs adds the "referenced_in" edge to the ListEntry entity by IDs.
func (_c *SeriesCreate) AddReferencedInIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddReferencedInIDs(ids...)
	return _c
}

// AddReferencedIn adds the "referenced_in" edges to the ListEntry entity.
func (_c *SeriesCreate) AddReferencedIn(v ...*ListEntry) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReferencedInIDs(ids...)
}

// AddCustomSequelOfIDs adds the "custom_sequel_of" edge to the ListEntry entity by IDs.
func (_c *SeriesCreate) AddCustomSequelOfIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddCustomSequelOfIDs(ids...)
	return _c
}

// AddCustomSequelOf adds the "custom_sequel_of" edges to the ListEntry entity.
func (_c *SeriesCreate) AddCustomSequelOf(v ...*ListEntry) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCustomSequelOfIDs(ids...)
}

// AddPrequelIDs adds the "prequels" edge to the Series entity by IDs.
func (_c *SeriesCreate) AddPrequelIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddPrequelIDs(ids...)
	return _c
}

// AddPrequels adds the "prequels" edges to the Series entity.
func (_c *SeriesCreate) AddPrequels(v ...*Series) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPrequelIDs(ids...)
}

// AddSequelIDs adds the "sequels" edge to the Series entity by IDs.
func (_c *SeriesCreate) AddSequelIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddSequelIDs(ids...)
	return _c
}

// AddSequels adds the "sequels" edges to the Series entity.
func (_c *SeriesCreate) AddSequels(v ...*Series) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSequelIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_c *SeriesCreate) Mutation() *SeriesMutation {
	return _c.mutation
}

// Save creates the Series in the database.
func (_c *SeriesCreate) Save(ctx context.Context) (*Series, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeriesCreate) SaveX(ctx context.Context) *Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SeriesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := series.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := series.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := series.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeriesCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Series.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Series.updated_at"`)}
	}
	if _, ok := _c.mutation.AnilistID(); !ok {
		return &ValidationError{Name: "anilist_id", err: errors.New(`ent: missing required field "Series.anilist_id"`)}
	}
	if _, ok := _c.mutation.TitleEnglish(); !ok {
		return &ValidationError{Name: "title_english", err: errors.New(`ent: missing required field "Series.title_english"`)}
	}
	if _, ok := _c.mutation.TitleNative(); !ok {
		return &ValidationError{Name: "title_native", err: errors.New(`ent: missing required field "Series.title_native"`)}
	}
	if _, ok := _c.mutation.TitleRomaji(); !ok {
		return &ValidationError{Name: "title_romaji", err: errors.New(`ent: missing required field "Series.title_romaji"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Series.description"`)}
	}
	if _, ok := _c.mutation.CoverImageURL(); !ok {
		return &ValidationError{Name: "cover_image_url", err: errors.New(`ent: missing required field "Series.cover_image_url"`)}
	}
	if _, ok := _c.mutation.Episodes(); !ok {
		return &ValidationError{Name: "episodes", err: errors.New(`ent: missing required field "Series.episodes"`)}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "Series.duration"`)}
	}
	return nil
}

func (_c *SeriesCreate) sqlSave(ctx context.Context) (*Series, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeriesCreate) createSpec() (*Series, *sqlgraph.CreateSpec) {
	var (
		_node = &Series{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(series.Table, sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SynchronizedAt(); ok {
		_spec.SetField(series.FieldSynchronizedAt, field.TypeTime, value)
		_node.SynchronizedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(series.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(series.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AnilistID(); ok {
		_spec.SetField(series.FieldAnilistID, field.TypeUint, value)
		_node.AnilistID = value
	}
	if value, ok := _c.mutation.TitleEnglish(); ok {
		_spec.SetField(series.FieldTitleEnglish, field.TypeString, value)
		_node.TitleEnglish = &value
	}
	if value, ok := _c.mutation.TitleNative(); ok {
		_spec.SetField(series.FieldTitleNative, field.TypeString, value)
		_node.TitleNative = &value
	}
	if value, ok := _c.mutation.TitleRomaji(); ok {
		_spec.SetField(series.FieldTitleRomaji, field.TypeString, value)
		_node.TitleRomaji = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CoverImageURL(); ok {
		_spec.SetField(series.FieldCoverImageURL, field.TypeString, value)
		_node.CoverImageURL = value
	}
	if value, ok := _c.mutation.Episodes(); ok {
		_spec.SetField(series.FieldEpisodes, field.TypeUint, value)
		_node.Episodes = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(series.FieldDuration, field.TypeInt64, value)
		_node.Duration = value
	}
	if nodes := _c.mutation.ReferencedInIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.ReferencedInTable,
			Columns: []string{series.ReferencedInColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomSequelOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   series.CustomSequelOfTable,
			Columns: []string{series.CustomSequelOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PrequelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   series.PrequelsTable,
			Columns: series.PrequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SequelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   series.SequelsTable,
			Columns: series.SequelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SeriesCreateBulk is the builder for creating many Series entities in bulk.
type SeriesCreateBulk struct {
	config
	err      error
	builders []*SeriesCreate
}

// Save creates the Series entities in the database.
func (_c *SeriesCreateBulk) Save(ctx context.Context) ([]*Series, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Series, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeriesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeriesCreateBulk) SaveX(ctx context.Context) []*Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
