// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chunk: typeof import('./src/components/Chunk.vue')['default']
    Entry: typeof import('./src/components/Entry/Entry.vue')['default']
    EntryContainer: typeof import('./src/components/Entry/EntryContainer.vue')['default']
    EntrySettings: typeof import('./src/components/Entry/EntrySettings.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IconMdiTranslate: typeof import('~icons/mdi/translate')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    ListStats: typeof import('./src/components/List/ListStats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./src/components/SettingsMenu.vue')['default']
    Sortable: typeof import('./src/components/utils/Sortable.vue')['default']
    UserComponent: typeof import('./src/components/UserComponent.vue')['default']
    UserLists: typeof import('./src/components/List/UserLists.vue')['default']
    UserSettingsMenu: typeof import('./src/components/UserSettingsMenu.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAppBarTitle: typeof import('vuetify/components')['VAppBarTitle']
    VAvatar: typeof import('vuetify/components')['VAvatar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VChip: typeof import('vuetify/components')['VChip']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDivider: typeof import('vuetify/components')['VDivider']
    VIcon: typeof import('vuetify/components')['VIcon']
    VImg: typeof import('vuetify/components')['VImg']
    VItem: typeof import('vuetify/components')['VItem']
    VItemGroup: typeof import('vuetify/components')['VItemGroup']
    VKbd: typeof import('vuetify/components')['VKbd']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VMenu: typeof import('vuetify/components')['VMenu']
    VRadio: typeof import('vuetify/components')['VRadio']
    VRadioGroup: typeof import('vuetify/components')['VRadioGroup']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VSwitch: typeof import('vuetify/components')['VSwitch']
    VTextField: typeof import('vuetify/components')['VTextField']
    VToolbarItems: typeof import('vuetify/components')['VToolbarItems']
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle']
  }
}
