version: 3

includes:
  tools:
    taskfile: '{{ .ToolDir }}/taskfile.yaml'
    internal: false

vars:
  AppDebug: 'false'

  Version:
    sh: echo "0.0.0-DEV.0"

  GitTag:
    sh: git describe 2>/dev/null || echo 'N/A'
  GitCommit:
    sh: git rev-parse --short HEAD 2>/dev/null

  ToolDir: 'tools'
  GOBIN:   'tools'

  Sqlc: { map: {
    Version: latest
  }}

  Gogio: { map: {
    Version: latest
  }}

  Goose: { map: {
    Version: latest
  }}

  Reflex: { map: {
    Version: latest
  }}

  Android: { map: {
    PlatformVersion:   '36', # Android 16
    BuildToolsVersion: '36.0.0',
    SdkRoot:           '{{ .ToolDir }}/android-sdk',
    NdkRoot:           '{{ .ToolDir }}/android-sdk/ndk-bundle',
    AppId:             'nl.jojoxd.anistats',
  }}

  GOPACKAGE: "anistats"

  GOARGS: |
    -ldflags '-X anistats/internal/constants/app.AppDebug={{.AppDebug}}' \
    -ldflags '-X anistats/internal/constants/version.gitTag="{{.GitTag}}"' \
    -ldflags '-X anistats/internal/constants/version.gitCommit="{{ .GitCommit }}"' \

tasks:
  generate:
    cmds:
      - task: generate:go
      - task: generate:sqlc

  serve:
    deps:
      - tools:installed

    cmd: "{{ .ROOT_DIR }}/{{ .GOBIN }}/reflex -s -g '**/*' -- go run -v -tags serveronly ./entry/cli/main.go serve"

  vet:
    ignore_error: true
    cmds:
      - task: vet:go
      - task: vet:sqlc

  build:
    cmds:
      - task: generate
      - task: build:linux:wayland
      - task: build:linux:x11
      - task: build:linux:server-only
      - task: build:android:client

  build:linux:wayland:
    cmds:
      - task: tools:installed
      - task: generate
      - cmd: |
          go build -v \
            -tags app,nox11,wayland \
            -o out/linux/wayland/anistats \
            {{ .GOARGS }} \
          {{ .GOPACKAGE }}/entry/cli/anistats

  build:linux:x11:
    cmds:
      - task: tools:installed
      - task: generate
      - cmd: |
          go build -v \
            -tags app,nowayland,x11 \
            -o out/linux/x11/anistats \
            {{ .GOARGS }} \
          {{ .GOPACKAGE }}/entry/cli/anistats

  build:linux:server-only:
    cmds:
      - task: tools:installed
      - task: generate
      - cmd: |
          go build -v \
            -tags serveronly \
            -o out/linux/server/anistats \
            {{ .GOARGS }} \
          {{ .GOPACKAGE }}/entry/cli/anistats

  build:android:client:
    sources:
      - './**/*.go'
      - './internal/app/resources/**/*'

    env:
      ANDROID_SDK_ROOT: '{{ .ROOT_DIR }}/{{ .Android.SdkRoot }}'
      ANDROID_NDK_ROOT: '{{ .ROOT_DIR }}/{{ .Android.NdkRoot }}'
      ANDROID_HOME:     '{{ .ROOT_DIR }}/{{ .Android.SdkRoot }}'

    cmds:
      - task: tools:installed
      - task: generate
      - cmd: mkdir -p out/android
      - cmd: |
         go run ../gio-cmd/gogio -x \
            -target android -buildmode exe -targetsdk {{ .Android.PlatformVersion }} \
            -icon internal/app/resources/icon_android.png \
            -appid {{ .Android.AppId }} \
            {{ .GOARGS }} \
            -tags app \
            -o out/android/{{ .Android.AppId }}.apk \
          {{ .GOPACKAGE }}/entry/android

      - cmd: 'echo "TODO: Build Android Apk from out/android {{ .Android.AppId }}.aar"'

  generate:go:
    sources: [ './**/*.go' ]
    cmd: go generate -v ./...

  generate:sqlc:
    dir: internal/server/dbal
    sources:
      - '**/*.sql'
    cmds:
      - task: tools:installed
      - cmd: '{{ .ROOT_DIR }}/{{ .GOBIN }}/sqlc generate'

  vet:sqlc:
    dir: internal/server/dbal
    cmds:
      - task: tools:installed
      - cmd: '{{ .ROOT_DIR }}/{{ .GOBIN }}/sqlc vet'
  vet:go:
    cmd: go vet ./...