/**
 * @file Automatically generated by barrelsby.
 */

export * from "./get-custom-lists-containing.gql";
export * from "./get-user-lists.gql";
export * from "./mutation/set-entry-for-custom-lists.gql";
