// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSynchronizedAt holds the string denoting the synchronized_at field in the database.
	FieldSynchronizedAt = "synchronized_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldAnilistID holds the string denoting the anilist_id field in the database.
	FieldAnilistID = "anilist_id"
	// EdgeLists holds the string denoting the lists edge name in mutations.
	EdgeLists = "lists"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ListsTable is the table that holds the lists relation/edge.
	ListsTable = "lists"
	// ListsInverseTable is the table name for the List entity.
	// It exists in this package in order to avoid circular dependency with the "list" package.
	ListsInverseTable = "lists"
	// ListsColumn is the table column denoting the lists relation/edge.
	ListsColumn = "user_lists"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldSynchronizedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldAvatarURL,
	FieldAnilistID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySynchronizedAt orders the results by the synchronized_at field.
func BySynchronizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSynchronizedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByAnilistID orders the results by the anilist_id field.
func ByAnilistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnilistID, opts...).ToFunc()
}

// ByListsCount orders the results by lists count.
func ByListsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newListsStep(), opts...)
	}
}

// ByLists orders the results by lists terms.
func ByLists(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newListsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ListsTable, ListsColumn),
	)
}
