/**
 * @file Automatically generated by barrelsby.
 */

export * from "./auth/auth.controller";
export * from "./list/list.controller";
export * from "./search/search-anime.controller";
export * from "./search/search-global.controller";
export * from "./user/user.controller";
