// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	Id            uuid.UUID
	Discriminator string
	UserID        uuid.UUID
	CreatedAt     time.Time
}

type ActivityMessage struct {
	Id         uuid.UUID
	ActivityID uuid.UUID
	AuthorID   uuid.UUID
	Message    string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type List struct {
	Id        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ListActivity struct {
	ActivityID uuid.UUID
	ListID     uuid.UUID
	Type       string
}

type ListEntry struct {
	Id              uuid.UUID
	ListID          uuid.UUID
	MediaID         uuid.UUID
	EpisodesWatched int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ListEntryActivity struct {
	ActivityID  uuid.UUID
	ListEntryID uuid.UUID
	Type        string
}

type ListEntrySetting struct {
	ListID uuid.UUID
}

type ListSetting struct {
	ListID uuid.UUID
}

type MediaExternalIdent struct {
	MediaID  uuid.UUID
	Source   string
	SourceID string
}

type MediaTranslation struct {
	MediaID      uuid.UUID
	LanguageCode string
	Translation  string
}

type Medium struct {
	Id                   uuid.UUID
	EpisodeTotal         int32
	EpisodeLengthMinutes int32
}

type User struct {
	Id           uuid.UUID
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserActivity struct {
	ActivityID uuid.UUID
	Type       string
}

type UserExternalIdent struct {
	UserID   uuid.UUID
	Source   string
	SourceID string
}
