// Code generated by ent, DO NOT EDIT.

package series

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the series type in the database.
	Label = "series"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSynchronizedAt holds the string denoting the synchronized_at field in the database.
	FieldSynchronizedAt = "synchronized_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAnilistID holds the string denoting the anilist_id field in the database.
	FieldAnilistID = "anilist_id"
	// FieldTitleEnglish holds the string denoting the title_english field in the database.
	FieldTitleEnglish = "title_english"
	// FieldTitleNative holds the string denoting the title_native field in the database.
	FieldTitleNative = "title_native"
	// FieldTitleRomaji holds the string denoting the title_romaji field in the database.
	FieldTitleRomaji = "title_romaji"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCoverImageURL holds the string denoting the cover_image_url field in the database.
	FieldCoverImageURL = "cover_image_url"
	// FieldEpisodes holds the string denoting the episodes field in the database.
	FieldEpisodes = "episodes"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// EdgeReferencedIn holds the string denoting the referenced_in edge name in mutations.
	EdgeReferencedIn = "referenced_in"
	// EdgeCustomSequelOf holds the string denoting the custom_sequel_of edge name in mutations.
	EdgeCustomSequelOf = "custom_sequel_of"
	// EdgePrequels holds the string denoting the prequels edge name in mutations.
	EdgePrequels = "prequels"
	// EdgeSequels holds the string denoting the sequels edge name in mutations.
	EdgeSequels = "sequels"
	// Table holds the table name of the series in the database.
	Table = "series"
	// ReferencedInTable is the table that holds the referenced_in relation/edge.
	ReferencedInTable = "list_entries"
	// ReferencedInInverseTable is the table name for the ListEntry entity.
	// It exists in this package in order to avoid circular dependency with the "listentry" package.
	ReferencedInInverseTable = "list_entries"
	// ReferencedInColumn is the table column denoting the referenced_in relation/edge.
	ReferencedInColumn = "list_entry_series"
	// CustomSequelOfTable is the table that holds the custom_sequel_of relation/edge.
	CustomSequelOfTable = "list_entries"
	// CustomSequelOfInverseTable is the table name for the ListEntry entity.
	// It exists in this package in order to avoid circular dependency with the "listentry" package.
	CustomSequelOfInverseTable = "list_entries"
	// CustomSequelOfColumn is the table column denoting the custom_sequel_of relation/edge.
	CustomSequelOfColumn = "list_entry_custom_sequel_series"
	// PrequelsTable is the table that holds the prequels relation/edge. The primary key declared below.
	PrequelsTable = "series_sequels"
	// SequelsTable is the table that holds the sequels relation/edge. The primary key declared below.
	SequelsTable = "series_sequels"
)

// Columns holds all SQL columns for series fields.
var Columns = []string{
	FieldID,
	FieldSynchronizedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAnilistID,
	FieldTitleEnglish,
	FieldTitleNative,
	FieldTitleRomaji,
	FieldDescription,
	FieldCoverImageURL,
	FieldEpisodes,
	FieldDuration,
}

var (
	// PrequelsPrimaryKey and PrequelsColumn2 are the table columns denoting the
	// primary key for the prequels relation (M2M).
	PrequelsPrimaryKey = []string{"series_id", "prequel_id"}
	// SequelsPrimaryKey and SequelsColumn2 are the table columns denoting the
	// primary key for the sequels relation (M2M).
	SequelsPrimaryKey = []string{"series_id", "prequel_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Series queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySynchronizedAt orders the results by the synchronized_at field.
func BySynchronizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSynchronizedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAnilistID orders the results by the anilist_id field.
func ByAnilistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnilistID, opts...).ToFunc()
}

// ByTitleEnglish orders the results by the title_english field.
func ByTitleEnglish(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleEnglish, opts...).ToFunc()
}

// ByTitleNative orders the results by the title_native field.
func ByTitleNative(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleNative, opts...).ToFunc()
}

// ByTitleRomaji orders the results by the title_romaji field.
func ByTitleRomaji(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleRomaji, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCoverImageURL orders the results by the cover_image_url field.
func ByCoverImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverImageURL, opts...).ToFunc()
}

// ByEpisodes orders the results by the episodes field.
func ByEpisodes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEpisodes, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByReferencedInCount orders the results by referenced_in count.
func ByReferencedInCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReferencedInStep(), opts...)
	}
}

// ByReferencedIn orders the results by referenced_in terms.
func ByReferencedIn(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferencedInStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCustomSequelOfCount orders the results by custom_sequel_of count.
func ByCustomSequelOfCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCustomSequelOfStep(), opts...)
	}
}

// ByCustomSequelOf orders the results by custom_sequel_of terms.
func ByCustomSequelOf(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomSequelOfStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPrequelsCount orders the results by prequels count.
func ByPrequelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrequelsStep(), opts...)
	}
}

// ByPrequels orders the results by prequels terms.
func ByPrequels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrequelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySequelsCount orders the results by sequels count.
func BySequelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSequelsStep(), opts...)
	}
}

// BySequels orders the results by sequels terms.
func BySequels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSequelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newReferencedInStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferencedInInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ReferencedInTable, ReferencedInColumn),
	)
}
func newCustomSequelOfStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomSequelOfInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, CustomSequelOfTable, CustomSequelOfColumn),
	)
}
func newPrequelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, PrequelsTable, PrequelsPrimaryKey...),
	)
}
func newSequelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, SequelsTable, SequelsPrimaryKey...),
	)
}
