// Code generated by ent, DO NOT EDIT.

package series

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"git.jojoxd.nl/projects/anistats/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldID, id))
}

// SynchronizedAt applies equality check predicate on the "synchronized_at" field. It's identical to SynchronizedAtEQ.
func SynchronizedAt(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldSynchronizedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldUpdatedAt, v))
}

// AnilistID applies equality check predicate on the "anilist_id" field. It's identical to AnilistIDEQ.
func AnilistID(v uint) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldAnilistID, v))
}

// TitleEnglish applies equality check predicate on the "title_english" field. It's identical to TitleEnglishEQ.
func TitleEnglish(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitleEnglish, v))
}

// TitleNative applies equality check predicate on the "title_native" field. It's identical to TitleNativeEQ.
func TitleNative(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitleNative, v))
}

// TitleRomaji applies equality check predicate on the "title_romaji" field. It's identical to TitleRomajiEQ.
func TitleRomaji(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitleRomaji, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldDescription, v))
}

// CoverImageURL applies equality check predicate on the "cover_image_url" field. It's identical to CoverImageURLEQ.
func CoverImageURL(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldCoverImageURL, v))
}

// Episodes applies equality check predicate on the "episodes" field. It's identical to EpisodesEQ.
func Episodes(v uint) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldEpisodes, v))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v time.Duration) predicate.Series {
	vc := int64(v)
	return predicate.Series(sql.FieldEQ(FieldDuration, vc))
}

// SynchronizedAtEQ applies the EQ predicate on the "synchronized_at" field.
func SynchronizedAtEQ(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldSynchronizedAt, v))
}

// SynchronizedAtNEQ applies the NEQ predicate on the "synchronized_at" field.
func SynchronizedAtNEQ(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldSynchronizedAt, v))
}

// SynchronizedAtIn applies the In predicate on the "synchronized_at" field.
func SynchronizedAtIn(vs ...time.Time) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldSynchronizedAt, vs...))
}

// SynchronizedAtNotIn applies the NotIn predicate on the "synchronized_at" field.
func SynchronizedAtNotIn(vs ...time.Time) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldSynchronizedAt, vs...))
}

// SynchronizedAtGT applies the GT predicate on the "synchronized_at" field.
func SynchronizedAtGT(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldSynchronizedAt, v))
}

// SynchronizedAtGTE applies the GTE predicate on the "synchronized_at" field.
func SynchronizedAtGTE(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldSynchronizedAt, v))
}

// SynchronizedAtLT applies the LT predicate on the "synchronized_at" field.
func SynchronizedAtLT(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldSynchronizedAt, v))
}

// SynchronizedAtLTE applies the LTE predicate on the "synchronized_at" field.
func SynchronizedAtLTE(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldSynchronizedAt, v))
}

// SynchronizedAtIsNil applies the IsNil predicate on the "synchronized_at" field.
func SynchronizedAtIsNil() predicate.Series {
	return predicate.Series(sql.FieldIsNull(FieldSynchronizedAt))
}

// SynchronizedAtNotNil applies the NotNil predicate on the "synchronized_at" field.
func SynchronizedAtNotNil() predicate.Series {
	return predicate.Series(sql.FieldNotNull(FieldSynchronizedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldUpdatedAt, v))
}

// AnilistIDEQ applies the EQ predicate on the "anilist_id" field.
func AnilistIDEQ(v uint) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldAnilistID, v))
}

// AnilistIDNEQ applies the NEQ predicate on the "anilist_id" field.
func AnilistIDNEQ(v uint) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldAnilistID, v))
}

// AnilistIDIn applies the In predicate on the "anilist_id" field.
func AnilistIDIn(vs ...uint) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldAnilistID, vs...))
}

// AnilistIDNotIn applies the NotIn predicate on the "anilist_id" field.
func AnilistIDNotIn(vs ...uint) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldAnilistID, vs...))
}

// AnilistIDGT applies the GT predicate on the "anilist_id" field.
func AnilistIDGT(v uint) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldAnilistID, v))
}

// AnilistIDGTE applies the GTE predicate on the "anilist_id" field.
func AnilistIDGTE(v uint) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldAnilistID, v))
}

// AnilistIDLT applies the LT predicate on the "anilist_id" field.
func AnilistIDLT(v uint) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldAnilistID, v))
}

// AnilistIDLTE applies the LTE predicate on the "anilist_id" field.
func AnilistIDLTE(v uint) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldAnilistID, v))
}

// TitleEnglishEQ applies the EQ predicate on the "title_english" field.
func TitleEnglishEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitleEnglish, v))
}

// TitleEnglishNEQ applies the NEQ predicate on the "title_english" field.
func TitleEnglishNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldTitleEnglish, v))
}

// TitleEnglishIn applies the In predicate on the "title_english" field.
func TitleEnglishIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldTitleEnglish, vs...))
}

// TitleEnglishNotIn applies the NotIn predicate on the "title_english" field.
func TitleEnglishNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldTitleEnglish, vs...))
}

// TitleEnglishGT applies the GT predicate on the "title_english" field.
func TitleEnglishGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldTitleEnglish, v))
}

// TitleEnglishGTE applies the GTE predicate on the "title_english" field.
func TitleEnglishGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldTitleEnglish, v))
}

// TitleEnglishLT applies the LT predicate on the "title_english" field.
func TitleEnglishLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldTitleEnglish, v))
}

// TitleEnglishLTE applies the LTE predicate on the "title_english" field.
func TitleEnglishLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldTitleEnglish, v))
}

// TitleEnglishContains applies the Contains predicate on the "title_english" field.
func TitleEnglishContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldTitleEnglish, v))
}

// TitleEnglishHasPrefix applies the HasPrefix predicate on the "title_english" field.
func TitleEnglishHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldTitleEnglish, v))
}

// TitleEnglishHasSuffix applies the HasSuffix predicate on the "title_english" field.
func TitleEnglishHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldTitleEnglish, v))
}

// TitleEnglishEqualFold applies the EqualFold predicate on the "title_english" field.
func TitleEnglishEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldTitleEnglish, v))
}

// TitleEnglishContainsFold applies the ContainsFold predicate on the "title_english" field.
func TitleEnglishContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldTitleEnglish, v))
}

// TitleNativeEQ applies the EQ predicate on the "title_native" field.
func TitleNativeEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitleNative, v))
}

// TitleNativeNEQ applies the NEQ predicate on the "title_native" field.
func TitleNativeNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldTitleNative, v))
}

// TitleNativeIn applies the In predicate on the "title_native" field.
func TitleNativeIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldTitleNative, vs...))
}

// TitleNativeNotIn applies the NotIn predicate on the "title_native" field.
func TitleNativeNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldTitleNative, vs...))
}

// TitleNativeGT applies the GT predicate on the "title_native" field.
func TitleNativeGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldTitleNative, v))
}

// TitleNativeGTE applies the GTE predicate on the "title_native" field.
func TitleNativeGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldTitleNative, v))
}

// TitleNativeLT applies the LT predicate on the "title_native" field.
func TitleNativeLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldTitleNative, v))
}

// TitleNativeLTE applies the LTE predicate on the "title_native" field.
func TitleNativeLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldTitleNative, v))
}

// TitleNativeContains applies the Contains predicate on the "title_native" field.
func TitleNativeContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldTitleNative, v))
}

// TitleNativeHasPrefix applies the HasPrefix predicate on the "title_native" field.
func TitleNativeHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldTitleNative, v))
}

// TitleNativeHasSuffix applies the HasSuffix predicate on the "title_native" field.
func TitleNativeHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldTitleNative, v))
}

// TitleNativeEqualFold applies the EqualFold predicate on the "title_native" field.
func TitleNativeEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldTitleNative, v))
}

// TitleNativeContainsFold applies the ContainsFold predicate on the "title_native" field.
func TitleNativeContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldTitleNative, v))
}

// TitleRomajiEQ applies the EQ predicate on the "title_romaji" field.
func TitleRomajiEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitleRomaji, v))
}

// TitleRomajiNEQ applies the NEQ predicate on the "title_romaji" field.
func TitleRomajiNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldTitleRomaji, v))
}

// TitleRomajiIn applies the In predicate on the "title_romaji" field.
func TitleRomajiIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldTitleRomaji, vs...))
}

// TitleRomajiNotIn applies the NotIn predicate on the "title_romaji" field.
func TitleRomajiNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldTitleRomaji, vs...))
}

// TitleRomajiGT applies the GT predicate on the "title_romaji" field.
func TitleRomajiGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldTitleRomaji, v))
}

// TitleRomajiGTE applies the GTE predicate on the "title_romaji" field.
func TitleRomajiGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldTitleRomaji, v))
}

// TitleRomajiLT applies the LT predicate on the "title_romaji" field.
func TitleRomajiLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldTitleRomaji, v))
}

// TitleRomajiLTE applies the LTE predicate on the "title_romaji" field.
func TitleRomajiLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldTitleRomaji, v))
}

// TitleRomajiContains applies the Contains predicate on the "title_romaji" field.
func TitleRomajiContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldTitleRomaji, v))
}

// TitleRomajiHasPrefix applies the HasPrefix predicate on the "title_romaji" field.
func TitleRomajiHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldTitleRomaji, v))
}

// TitleRomajiHasSuffix applies the HasSuffix predicate on the "title_romaji" field.
func TitleRomajiHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldTitleRomaji, v))
}

// TitleRomajiEqualFold applies the EqualFold predicate on the "title_romaji" field.
func TitleRomajiEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldTitleRomaji, v))
}

// TitleRomajiContainsFold applies the ContainsFold predicate on the "title_romaji" field.
func TitleRomajiContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldTitleRomaji, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldDescription, v))
}

// CoverImageURLEQ applies the EQ predicate on the "cover_image_url" field.
func CoverImageURLEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldCoverImageURL, v))
}

// CoverImageURLNEQ applies the NEQ predicate on the "cover_image_url" field.
func CoverImageURLNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldCoverImageURL, v))
}

// CoverImageURLIn applies the In predicate on the "cover_image_url" field.
func CoverImageURLIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldCoverImageURL, vs...))
}

// CoverImageURLNotIn applies the NotIn predicate on the "cover_image_url" field.
func CoverImageURLNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldCoverImageURL, vs...))
}

// CoverImageURLGT applies the GT predicate on the "cover_image_url" field.
func CoverImageURLGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldCoverImageURL, v))
}

// CoverImageURLGTE applies the GTE predicate on the "cover_image_url" field.
func CoverImageURLGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldCoverImageURL, v))
}

// CoverImageURLLT applies the LT predicate on the "cover_image_url" field.
func CoverImageURLLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldCoverImageURL, v))
}

// CoverImageURLLTE applies the LTE predicate on the "cover_image_url" field.
func CoverImageURLLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldCoverImageURL, v))
}

// CoverImageURLContains applies the Contains predicate on the "cover_image_url" field.
func CoverImageURLContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldCoverImageURL, v))
}

// CoverImageURLHasPrefix applies the HasPrefix predicate on the "cover_image_url" field.
func CoverImageURLHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldCoverImageURL, v))
}

// CoverImageURLHasSuffix applies the HasSuffix predicate on the "cover_image_url" field.
func CoverImageURLHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldCoverImageURL, v))
}

// CoverImageURLEqualFold applies the EqualFold predicate on the "cover_image_url" field.
func CoverImageURLEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldCoverImageURL, v))
}

// CoverImageURLContainsFold applies the ContainsFold predicate on the "cover_image_url" field.
func CoverImageURLContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldCoverImageURL, v))
}

// EpisodesEQ applies the EQ predicate on the "episodes" field.
func EpisodesEQ(v uint) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldEpisodes, v))
}

// EpisodesNEQ applies the NEQ predicate on the "episodes" field.
func EpisodesNEQ(v uint) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldEpisodes, v))
}

// EpisodesIn applies the In predicate on the "episodes" field.
func EpisodesIn(vs ...uint) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldEpisodes, vs...))
}

// EpisodesNotIn applies the NotIn predicate on the "episodes" field.
func EpisodesNotIn(vs ...uint) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldEpisodes, vs...))
}

// EpisodesGT applies the GT predicate on the "episodes" field.
func EpisodesGT(v uint) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldEpisodes, v))
}

// EpisodesGTE applies the GTE predicate on the "episodes" field.
func EpisodesGTE(v uint) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldEpisodes, v))
}

// EpisodesLT applies the LT predicate on the "episodes" field.
func EpisodesLT(v uint) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldEpisodes, v))
}

// EpisodesLTE applies the LTE predicate on the "episodes" field.
func EpisodesLTE(v uint) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldEpisodes, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v time.Duration) predicate.Series {
	vc := int64(v)
	return predicate.Series(sql.FieldEQ(FieldDuration, vc))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v time.Duration) predicate.Series {
	vc := int64(v)
	return predicate.Series(sql.FieldNEQ(FieldDuration, vc))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...time.Duration) predicate.Series {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.Series(sql.FieldIn(FieldDuration, v...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...time.Duration) predicate.Series {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.Series(sql.FieldNotIn(FieldDuration, v...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v time.Duration) predicate.Series {
	vc := int64(v)
	return predicate.Series(sql.FieldGT(FieldDuration, vc))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v time.Duration) predicate.Series {
	vc := int64(v)
	return predicate.Series(sql.FieldGTE(FieldDuration, vc))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v time.Duration) predicate.Series {
	vc := int64(v)
	return predicate.Series(sql.FieldLT(FieldDuration, vc))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v time.Duration) predicate.Series {
	vc := int64(v)
	return predicate.Series(sql.FieldLTE(FieldDuration, vc))
}

// HasReferencedIn applies the HasEdge predicate on the "referenced_in" edge.
func HasReferencedIn() predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ReferencedInTable, ReferencedInColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferencedInWith applies the HasEdge predicate on the "referenced_in" edge with a given conditions (other predicates).
func HasReferencedInWith(preds ...predicate.ListEntry) predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := newReferencedInStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomSequelOf applies the HasEdge predicate on the "custom_sequel_of" edge.
func HasCustomSequelOf() predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, CustomSequelOfTable, CustomSequelOfColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomSequelOfWith applies the HasEdge predicate on the "custom_sequel_of" edge with a given conditions (other predicates).
func HasCustomSequelOfWith(preds ...predicate.ListEntry) predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := newCustomSequelOfStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPrequels applies the HasEdge predicate on the "prequels" edge.
func HasPrequels() predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, PrequelsTable, PrequelsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrequelsWith applies the HasEdge predicate on the "prequels" edge with a given conditions (other predicates).
func HasPrequelsWith(preds ...predicate.Series) predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := newPrequelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSequels applies the HasEdge predicate on the "sequels" edge.
func HasSequels() predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, SequelsTable, SequelsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSequelsWith applies the HasEdge predicate on the "sequels" edge with a given conditions (other predicates).
func HasSequelsWith(preds ...predicate.Series) predicate.Series {
	return predicate.Series(func(s *sql.Selector) {
		step := newSequelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Series) predicate.Series {
	return predicate.Series(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Series) predicate.Series {
	return predicate.Series(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Series) predicate.Series {
	return predicate.Series(sql.NotPredicates(p))
}
