// Code generated by ent, DO NOT EDIT.

package listentry

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"git.jojoxd.nl/projects/anistats/backend/api"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the listentry type in the database.
	Label = "list_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAnilistID holds the string denoting the anilist_id field in the database.
	FieldAnilistID = "anilist_id"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldMultiplier holds the string denoting the multiplier field in the database.
	FieldMultiplier = "multiplier"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldStartAt holds the string denoting the start_at field in the database.
	FieldStartAt = "start_at"
	// FieldSplit holds the string denoting the split field in the database.
	FieldSplit = "split"
	// FieldSplitSequelEntry holds the string denoting the split_sequel_entry field in the database.
	FieldSplitSequelEntry = "split_sequel_entry"
	// EdgeList holds the string denoting the list edge name in mutations.
	EdgeList = "list"
	// EdgeSeries holds the string denoting the series edge name in mutations.
	EdgeSeries = "series"
	// EdgeCustomSequelSeries holds the string denoting the custom_sequel_series edge name in mutations.
	EdgeCustomSequelSeries = "custom_sequel_series"
	// Table holds the table name of the listentry in the database.
	Table = "list_entries"
	// ListTable is the table that holds the list relation/edge.
	ListTable = "list_entries"
	// ListInverseTable is the table name for the List entity.
	// It exists in this package in order to avoid circular dependency with the "list" package.
	ListInverseTable = "lists"
	// ListColumn is the table column denoting the list relation/edge.
	ListColumn = "list_entries"
	// SeriesTable is the table that holds the series relation/edge.
	SeriesTable = "list_entries"
	// SeriesInverseTable is the table name for the Series entity.
	// It exists in this package in order to avoid circular dependency with the "series" package.
	SeriesInverseTable = "series"
	// SeriesColumn is the table column denoting the series relation/edge.
	SeriesColumn = "list_entry_series"
	// CustomSequelSeriesTable is the table that holds the custom_sequel_series relation/edge.
	CustomSequelSeriesTable = "list_entries"
	// CustomSequelSeriesInverseTable is the table name for the Series entity.
	// It exists in this package in order to avoid circular dependency with the "series" package.
	CustomSequelSeriesInverseTable = "series"
	// CustomSequelSeriesColumn is the table column denoting the custom_sequel_series relation/edge.
	CustomSequelSeriesColumn = "list_entry_custom_sequel_series"
)

// Columns holds all SQL columns for listentry fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAnilistID,
	FieldState,
	FieldProgress,
	FieldMultiplier,
	FieldOrder,
	FieldStartAt,
	FieldSplit,
	FieldSplitSequelEntry,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "list_entries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"list_entries",
	"list_entry_series",
	"list_entry_custom_sequel_series",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress uint
	// DefaultMultiplier holds the default value on creation for the "multiplier" field.
	DefaultMultiplier float64
	// DefaultSplitSequelEntry holds the default value on creation for the "split_sequel_entry" field.
	DefaultSplitSequelEntry bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s api.EntryStatus) error {
	switch s.String() {
	case "completed", "current", "dropped", "paused", "planning", "repeating":
		return nil
	default:
		return fmt.Errorf("listentry: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the ListEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAnilistID orders the results by the anilist_id field.
func ByAnilistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnilistID, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByMultiplier orders the results by the multiplier field.
func ByMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMultiplier, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// ByStartAt orders the results by the start_at field.
func ByStartAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartAt, opts...).ToFunc()
}

// BySplit orders the results by the split field.
func BySplit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSplit, opts...).ToFunc()
}

// BySplitSequelEntry orders the results by the split_sequel_entry field.
func BySplitSequelEntry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSplitSequelEntry, opts...).ToFunc()
}

// ByListField orders the results by list field.
func ByListField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListStep(), sql.OrderByField(field, opts...))
	}
}

// BySeriesField orders the results by series field.
func BySeriesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeriesStep(), sql.OrderByField(field, opts...))
	}
}

// ByCustomSequelSeriesField orders the results by custom_sequel_series field.
func ByCustomSequelSeriesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomSequelSeriesStep(), sql.OrderByField(field, opts...))
	}
}
func newListStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ListTable, ListColumn),
	)
}
func newSeriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SeriesTable, SeriesColumn),
	)
}
func newCustomSequelSeriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomSequelSeriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CustomSequelSeriesTable, CustomSequelSeriesColumn),
	)
}
