// Code generated by ent, DO NOT EDIT.

package listentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"git.jojoxd.nl/projects/anistats/backend/api"
	"git.jojoxd.nl/projects/anistats/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// AnilistID applies equality check predicate on the "anilist_id" field. It's identical to AnilistIDEQ.
func AnilistID(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldAnilistID, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldProgress, v))
}

// Multiplier applies equality check predicate on the "multiplier" field. It's identical to MultiplierEQ.
func Multiplier(v float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldMultiplier, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldOrder, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldStartAt, v))
}

// Split applies equality check predicate on the "split" field. It's identical to SplitEQ.
func Split(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldSplit, v))
}

// SplitSequelEntry applies equality check predicate on the "split_sequel_entry" field. It's identical to SplitSequelEntryEQ.
func SplitSequelEntry(v bool) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldSplitSequelEntry, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// AnilistIDEQ applies the EQ predicate on the "anilist_id" field.
func AnilistIDEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldAnilistID, v))
}

// AnilistIDNEQ applies the NEQ predicate on the "anilist_id" field.
func AnilistIDNEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldAnilistID, v))
}

// AnilistIDIn applies the In predicate on the "anilist_id" field.
func AnilistIDIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldAnilistID, vs...))
}

// AnilistIDNotIn applies the NotIn predicate on the "anilist_id" field.
func AnilistIDNotIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldAnilistID, vs...))
}

// AnilistIDGT applies the GT predicate on the "anilist_id" field.
func AnilistIDGT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldAnilistID, v))
}

// AnilistIDGTE applies the GTE predicate on the "anilist_id" field.
func AnilistIDGTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldAnilistID, v))
}

// AnilistIDLT applies the LT predicate on the "anilist_id" field.
func AnilistIDLT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldAnilistID, v))
}

// AnilistIDLTE applies the LTE predicate on the "anilist_id" field.
func AnilistIDLTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldAnilistID, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v api.EntryStatus) predicate.ListEntry {
	vc := v
	return predicate.ListEntry(sql.FieldEQ(FieldState, vc))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v api.EntryStatus) predicate.ListEntry {
	vc := v
	return predicate.ListEntry(sql.FieldNEQ(FieldState, vc))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...api.EntryStatus) predicate.ListEntry {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ListEntry(sql.FieldIn(FieldState, v...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...api.EntryStatus) predicate.ListEntry {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ListEntry(sql.FieldNotIn(FieldState, v...))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldProgress, v))
}

// MultiplierEQ applies the EQ predicate on the "multiplier" field.
func MultiplierEQ(v float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldMultiplier, v))
}

// MultiplierNEQ applies the NEQ predicate on the "multiplier" field.
func MultiplierNEQ(v float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldMultiplier, v))
}

// MultiplierIn applies the In predicate on the "multiplier" field.
func MultiplierIn(vs ...float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldMultiplier, vs...))
}

// MultiplierNotIn applies the NotIn predicate on the "multiplier" field.
func MultiplierNotIn(vs ...float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldMultiplier, vs...))
}

// MultiplierGT applies the GT predicate on the "multiplier" field.
func MultiplierGT(v float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldMultiplier, v))
}

// MultiplierGTE applies the GTE predicate on the "multiplier" field.
func MultiplierGTE(v float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldMultiplier, v))
}

// MultiplierLT applies the LT predicate on the "multiplier" field.
func MultiplierLT(v float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldMultiplier, v))
}

// MultiplierLTE applies the LTE predicate on the "multiplier" field.
func MultiplierLTE(v float64) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldMultiplier, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldOrder, v))
}

// OrderIsNil applies the IsNil predicate on the "order" field.
func OrderIsNil() predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIsNull(FieldOrder))
}

// OrderNotNil applies the NotNil predicate on the "order" field.
func OrderNotNil() predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotNull(FieldOrder))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldStartAt, v))
}

// StartAtIsNil applies the IsNil predicate on the "start_at" field.
func StartAtIsNil() predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIsNull(FieldStartAt))
}

// StartAtNotNil applies the NotNil predicate on the "start_at" field.
func StartAtNotNil() predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotNull(FieldStartAt))
}

// SplitEQ applies the EQ predicate on the "split" field.
func SplitEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldSplit, v))
}

// SplitNEQ applies the NEQ predicate on the "split" field.
func SplitNEQ(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldSplit, v))
}

// SplitIn applies the In predicate on the "split" field.
func SplitIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIn(FieldSplit, vs...))
}

// SplitNotIn applies the NotIn predicate on the "split" field.
func SplitNotIn(vs ...uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotIn(FieldSplit, vs...))
}

// SplitGT applies the GT predicate on the "split" field.
func SplitGT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGT(FieldSplit, v))
}

// SplitGTE applies the GTE predicate on the "split" field.
func SplitGTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldGTE(FieldSplit, v))
}

// SplitLT applies the LT predicate on the "split" field.
func SplitLT(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLT(FieldSplit, v))
}

// SplitLTE applies the LTE predicate on the "split" field.
func SplitLTE(v uint) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldLTE(FieldSplit, v))
}

// SplitIsNil applies the IsNil predicate on the "split" field.
func SplitIsNil() predicate.ListEntry {
	return predicate.ListEntry(sql.FieldIsNull(FieldSplit))
}

// SplitNotNil applies the NotNil predicate on the "split" field.
func SplitNotNil() predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNotNull(FieldSplit))
}

// SplitSequelEntryEQ applies the EQ predicate on the "split_sequel_entry" field.
func SplitSequelEntryEQ(v bool) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldEQ(FieldSplitSequelEntry, v))
}

// SplitSequelEntryNEQ applies the NEQ predicate on the "split_sequel_entry" field.
func SplitSequelEntryNEQ(v bool) predicate.ListEntry {
	return predicate.ListEntry(sql.FieldNEQ(FieldSplitSequelEntry, v))
}

// HasList applies the HasEdge predicate on the "list" edge.
func HasList() predicate.ListEntry {
	return predicate.ListEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ListTable, ListColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasListWith applies the HasEdge predicate on the "list" edge with a given conditions (other predicates).
func HasListWith(preds ...predicate.List) predicate.ListEntry {
	return predicate.ListEntry(func(s *sql.Selector) {
		step := newListStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSeries applies the HasEdge predicate on the "series" edge.
func HasSeries() predicate.ListEntry {
	return predicate.ListEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SeriesTable, SeriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeriesWith applies the HasEdge predicate on the "series" edge with a given conditions (other predicates).
func HasSeriesWith(preds ...predicate.Series) predicate.ListEntry {
	return predicate.ListEntry(func(s *sql.Selector) {
		step := newSeriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomSequelSeries applies the HasEdge predicate on the "custom_sequel_series" edge.
func HasCustomSequelSeries() predicate.ListEntry {
	return predicate.ListEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CustomSequelSeriesTable, CustomSequelSeriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomSequelSeriesWith applies the HasEdge predicate on the "custom_sequel_series" edge with a given conditions (other predicates).
func HasCustomSequelSeriesWith(preds ...predicate.Series) predicate.ListEntry {
	return predicate.ListEntry(func(s *sql.Selector) {
		step := newCustomSequelSeriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ListEntry) predicate.ListEntry {
	return predicate.ListEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ListEntry) predicate.ListEntry {
	return predicate.ListEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ListEntry) predicate.ListEntry {
	return predicate.ListEntry(sql.NotPredicates(p))
}
