[package]
name = "anistats_core_ffi"
version = "0.1.0"
edition = "2021"
authors = [
    "Joey Vos <contact@jojoxd.nl> (https://jojoxd.nl)"
]

[lib]
name = "anistats_core_ffi"
crate-type = ["cdylib"]

[dependencies]
anistats_core = { path = "../anistats_core" }
