// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ListsColumns holds the columns for the "lists" table.
	ListsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "synchronized_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "stack_size", Type: field.TypeUint, Default: 4},
		{Name: "allow_chunk_merge", Type: field.TypeBool, Default: true},
		{Name: "max_chunk_length", Type: field.TypeUint, Default: 120},
		{Name: "max_chunk_join_length", Type: field.TypeUint, Default: 180},
		{Name: "user_lists", Type: field.TypeUUID, Nullable: true},
	}
	// ListsTable holds the schema information for the "lists" table.
	ListsTable = &schema.Table{
		Name:       "lists",
		Columns:    ListsColumns,
		PrimaryKey: []*schema.Column{ListsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lists_users_lists",
				Columns:    []*schema.Column{ListsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ListEntriesColumns holds the columns for the "list_entries" table.
	ListEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "anilist_id", Type: field.TypeUint},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"completed", "current", "dropped", "paused", "planning", "repeating"}},
		{Name: "progress", Type: field.TypeUint, Default: 0},
		{Name: "multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "order", Type: field.TypeUint, Nullable: true},
		{Name: "start_at", Type: field.TypeUint, Nullable: true},
		{Name: "split", Type: field.TypeUint, Nullable: true},
		{Name: "split_sequel_entry", Type: field.TypeBool, Default: false},
		{Name: "list_entries", Type: field.TypeUUID, Nullable: true},
		{Name: "list_entry_series", Type: field.TypeUUID, Nullable: true},
		{Name: "list_entry_custom_sequel_series", Type: field.TypeUUID, Nullable: true},
	}
	// ListEntriesTable holds the schema information for the "list_entries" table.
	ListEntriesTable = &schema.Table{
		Name:       "list_entries",
		Columns:    ListEntriesColumns,
		PrimaryKey: []*schema.Column{ListEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "list_entries_lists_entries",
				Columns:    []*schema.Column{ListEntriesColumns[11]},
				RefColumns: []*schema.Column{ListsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "list_entries_series_series",
				Columns:    []*schema.Column{ListEntriesColumns[12]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "list_entries_series_custom_sequel_series",
				Columns:    []*schema.Column{ListEntriesColumns[13]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SeriesColumns holds the columns for the "series" table.
	SeriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "synchronized_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "anilist_id", Type: field.TypeUint, Unique: true},
		{Name: "title_english", Type: field.TypeString},
		{Name: "title_native", Type: field.TypeString},
		{Name: "title_romaji", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "cover_image_url", Type: field.TypeString},
		{Name: "episodes", Type: field.TypeUint},
		{Name: "duration", Type: field.TypeInt64},
	}
	// SeriesTable holds the schema information for the "series" table.
	SeriesTable = &schema.Table{
		Name:       "series",
		Columns:    SeriesColumns,
		PrimaryKey: []*schema.Column{SeriesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "synchronized_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "avatar_url", Type: field.TypeString},
		{Name: "anilist_id", Type: field.TypeUint, Unique: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// SeriesSequelsColumns holds the columns for the "series_sequels" table.
	SeriesSequelsColumns = []*schema.Column{
		{Name: "series_id", Type: field.TypeUUID},
		{Name: "prequel_id", Type: field.TypeUUID},
	}
	// SeriesSequelsTable holds the schema information for the "series_sequels" table.
	SeriesSequelsTable = &schema.Table{
		Name:       "series_sequels",
		Columns:    SeriesSequelsColumns,
		PrimaryKey: []*schema.Column{SeriesSequelsColumns[0], SeriesSequelsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "series_sequels_series_id",
				Columns:    []*schema.Column{SeriesSequelsColumns[0]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "series_sequels_prequel_id",
				Columns:    []*schema.Column{SeriesSequelsColumns[1]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ListsTable,
		ListEntriesTable,
		SeriesTable,
		UsersTable,
		SeriesSequelsTable,
	}
)

func init() {
	ListsTable.ForeignKeys[0].RefTable = UsersTable
	ListEntriesTable.ForeignKeys[0].RefTable = ListsTable
	ListEntriesTable.ForeignKeys[1].RefTable = SeriesTable
	ListEntriesTable.ForeignKeys[2].RefTable = SeriesTable
	SeriesSequelsTable.ForeignKeys[0].RefTable = SeriesTable
	SeriesSequelsTable.ForeignKeys[1].RefTable = SeriesTable
}
