// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// List is the predicate function for list builders.
type List func(*sql.Selector)

// ListEntry is the predicate function for listentry builders.
type ListEntry func(*sql.Selector)

// Series is the predicate function for series builders.
type Series func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
