name: anistats_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # anistats_api:
  #   path: ../anistats_api

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  stream_transform: ^2.1.0

  go_router: ^14.2.3

  intl: ^0.19.0
  intl_utils: ^2.8.7

  # shared_preferences: ^2.2.3
  equatable: ^2.0.5
  uuid: ^4.4.2
  formz: ^0.7.0

  anistats_api:
    path: ../anistats_api

  authentication_repository:
    path: ../internal/authentication_repository
  
  user_repository:
    path: ../internal/user_repository
  logging: ^1.2.0
  provider: ^6.1.2
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # flutter_gen_runner: ^5.6.0

  build_runner: ^2.4.11
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true

  generate: true

  # assets:
  #   - assets/images/
  
# flutter_gen:
#   output: lib/gen

#   colors:
#     inputs:
#       - assets/color/colors.xml

# flutter_intl:
#   enabled: true
