[package]
name = "anilist"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
reqwest = "0.11.26"
graphql_client = { version = "0.13.0" }
